### ISSUE TITLE
Error in initial setup

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#10]
I cloned the repo and did everything with npm and `lerna bootstrap` kept on failing when it came across any `jsx`. I tried removing the postinstall script that triggered lerna but now gatsby wouldn't build the site. I updated to `gatsby@1.0.0-alpha20` and it tripped up at

```sh
ERROR in ./.cache/dev-404-page.js
Module not found: Error: Cannot resolve module 'gatsby-link' in /home/stuart/guides/.cache
 @ ./.cache/dev-404-page.js 15:18-40
```

**Comment by Bouncey** [comment]
@kuriakinzeng

**Comment by kuriakinzeng** [comment]
Hi @Bouncey to set up, you just have to cd to `www` and run `npm i`. Also I have just solved an error, so make sure you get the latest version.

**Comment by kuriakinzeng** [comment]
That said, I realize there is an error if we run `npm install` at the root directory (not `www`) that needed to be fixed.

**Comment by kuriakinzeng** [comment]
Oops
