### ISSUE TITLE
Responsiveness / Styling

### ISSUE THREAD

**Issue by alan-luo** [freeCodeCamp/guides#103]
**Issue**

Guide sidebar feels unresponsive. It's not obvious that it's clickable. For instance, I tried to click `audio`, which currently has no sub-pages, and thus did not expand. I thought my click didn't register. (It did.)

**Solution**

Add `cursor:pointer` on hover.

**Comment by Bouncey** [comment]
The side nav will be removed shortly

**Comment by alan-luo** [comment]
Oh, OK. Thanks for letting me know.
