### ISSUE TITLE
React.DOM.style deprecated

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#113]
When running the development version of guides (_npm run dev_) I see a warning message that states:

> Warning: Accessing factories like React.DOM.style has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

I'm not sure what needs to be done to correct this warning however it's a matter of concern I figured I would bring up.

**Comment by Bouncey** [comment]
This is being used by one of the packages imported by gatsby, I am yet to figure which one it is. We are certainly not using it directly.

**Comment by nsuchy** [comment]
@Bouncey I'm still learning when it comes to React and Node and am not sure where to get started in tracking this issue down. Do you think this issue will resolve itself or will we need to either replace or write an update to the package causing the issue?

**Comment by Bouncey** [comment]
I'm sure it will filter down before react v16 is launched

**Comment by nsuchy** [comment]
Well let's keep an eye on it for now and if it becomes a severe issue and isn't patched before react v16 we should take further action.

**Comment by Bouncey** [comment]
I can't remember seeing this lately. Is it still a thing? @nsuchy @systimotic ?

**Comment by nsuchy** [comment]
I haven't seen the error, I'll run the latest version of guides later today and will post an update. If the error is gone on my end I'll close this issue.

**Comment by systimotic** [comment]
I do remember seeing this originally, but it's been gone for a little while now. I'm closing this. @nsuchy If you're still seeing this warning, please reopen! For now, happy coding!
