### ISSUE TITLE
Dynamic meta data for Twitter and Facebook cards

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#1297]
Currently Guide articles don't get their own cards on Twitter or Facebook. 

We want to turn raw URLs like this:

![quincy_larson_on_twitter___test_article_https___t_co_acac3vne2i_](https://user-images.githubusercontent.com/985197/31762147-ed0b530a-b47f-11e7-9671-161b3ec3ca17.png)

Into nice looking cards like this:

![quincy_larson_on_twitter___test_https___t_co_a4uwqx6gfz_](https://user-images.githubusercontent.com/985197/31762201-1650f954-b480-11e7-8c2e-23cbf698a0d5.png)

This involves creating meta tags, like the ones we use here: https://github.com/freeCodeCamp/donate/blob/master/index.html

We would want to dynamically update the article title and other meta information based on the individual article.

@systimotic @Bouncey Do you have any thoughts on the best way to do this?

**Comment by LulaV14** [comment]
Hi @QuincyLarson,  may I help with this?

**Comment by soueuls** [comment]
I am interested to work on this with @LulaV14 if she is in!

I made some research and twitter partially support the OpenGraph protocol as a fallback (we should favor it over the native twitter protocol this way we get twitter/facebook without too much code duplication.

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@freeCodeCamp" />
<meta name="twitter:creator" content="X" />
<meta property="og:url" content="X" />
<meta property="og:title" content="X" />
<meta property="og:description" content="X" />
<meta property="og:image" content="X" />
```
As you can see the two first meta tags can be set statically.

- twitter:creator we could allow the writer to add an author tag in the article front matter (and have FreeCodeCamp as a fallback) or simply recognize the fully open source nature of these guides and statically set the author to be FreeCodeCamp.
- og:url is trivial to set dynamically.
- og:title we could use the title set in the article front matter (but then we lose some context), the title of javascript's break statement is simply called **break statement*. Thus, I propose to use the breadcrumb smartly concatenating the first (giving the general context) with the last (giving the specifics)
- og:description could be the first paragraph?
- og:image we could build a script fetching the first image of the article matching a decent twitter/facebook ration.

I am curious to get your feedbacks, let's discuss and tackle this 🤓

**Comment by QuincyLarson** [comment]
@LulaV14 @soueuls Yes - we would welcome your help with this. Would the two of you be interested in pairing on this? This is a high priority.

Regarding @soueuls's questions:

- Yes - for the og:title we should incorporate the breadcrumbs: "JavaScript - Break Statement | freeCodeCamp Guide" or even "CSS - Selectors - Attribute - Class | freeCodeCamp Guide" - can you think of a way to handle arbitrarily deep nesting this way?

- Yes - I think the first paragraph is ideal for the og:description.

- for og:image we could fetch the first image, and as a fallback just show the freeCodeCamp logo: https://s3.amazonaws.com/freecodecamp/freecodecamp-square-logo-large.jpg

**Comment by LulaV14** [comment]
Hi @soueuls, I'll be glad to work with you 😊 and I agree with what you say. 
So what I was thinking is maybe we can have the meta tags for 'twitter:card', 'twitter:site', and 'twitter:creator' in the 'meta.js' file like this:

```
import React from 'react';

const meta = [
  <meta charSet='utf-8' />,
  <meta
    content='IE=edge'
    httpEquiv='X-UA-Compatible'
  />,
  <meta
    content='width=device-width, initial-scale=1.0'
    name='viewport'
  />,
  <meta 
    name="twitter:card" 
    content="summary" 
  />,
  <meta 
    name="twitter:site" 
    content="@freeCodeCamp" 
  />,
  <meta 
    name="twitter:creator" 
    content="freeCodeCamp" 
  />
];

export default meta;
```

And for the remaining parts I like the idea about the Breadcrumbs, and I think it will not be that difficult maybe if in the 'Article.jsx' file we use just the split and titleify of the pathname like this:

```
  const pathMap = pathname
    .replace(/^\/([a-z0-9/-]+[^/])\/?$/i, '$1')
    .split('/');

  var metaTitle = '';
  pathMap.forEach((title, i) => {
    if(i == pathMap.length-1)
      metaTitle += titleify(title);
    else
      metaTitle += titleify(title + ' | ');
  });
```

And then only use the 'metaTitle' var in the Helmet component as well as the meta for og:url like this:
```
  <div>
      <Helmet>
        <title>{ `${title} | freeCodeCamp Guide` }</title>
        <link
          href={ `https://guide.freecodecamp.org${slug}` }
          rel='canonical'
        />
        <meta 
        property="og:url" 
        content={ `https://guide.freecodecamp.org${slug}` }
        />
        <meta 
          property="og:title"
          content={ `${metaTitle}` }
        />
      </Helmet>
      <Breadcrumbs path={ pathname } />
      <div
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
```

But I tested it and it didn't display what I put inside 'Helmet' in the Article.jsx file... maybe you can help me figure that out.. where would you put it?

**Comment by soueuls** [comment]
@LulaV14 I think meta.js is the perfect place for these twitter tags, I am not very well aware of what Helmet is doing (I will read about it tomorrow on my way to work and build you a working solution for that), it looks obvious that it's the right place to add it, I don't know why it does not work though.

But, the more I think about it, the more I think building the title from the breadcrumb is a fragile solution, this would add a tight coupling to it. Building up based on the URL might be more resilient to changes.

What do you think?

-----

Also @QuincyLarson what is your preferred policy for the twitter:creator? Should we go the easy way and statically set it to "freecodecamp" (which I think, also goes well with the nature of freecodecamp of making it one egoless community as a whole) or should we think of a dynamic strategy to set twitter:creator with the real author identity?

**Comment by LulaV14** [comment]
@soueuls Ok great 😊 ! And about the title I believe that it's ok to handle it the way I put it in the example using the 'pathname' constant that we already have in the Article.jsx file. 

Maybe it's a little confusing because here we don't see all the files so what I'm going to do is create a PR with the changes that I have so you can test it and tell me what's wrong with the code and if you have a better solution also upload it please :)

PS: I haven't done a PR with more than one people working on it so if I'm doing something wrong please tell me.

**Comment by systimotic** [comment]
Thanks for adding this @LulaV14!
