### ISSUE TITLE
Remove stub from article on iframes

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#134]
The Stub needs to be removed from this article.

https://github.com/freeCodeCamp/guides/blob/b35ec79ed1223c3ea480c49491a6a79cf21ce3fa/src/pages/articles/html/iframes/index.md

**Comment by invinciblycool** [comment]
I have removed the stub and opened a PR regarding the same

**Comment by Bouncey** [comment]
Closed via #138
