### ISSUE TITLE
Edit README to remove meta command

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#136]
https://github.com/freeCodeCamp/guides/blob/master/README.md#how-to-contribute

This section in the README references a long forgotten script. 

It needs to be removed. 

It currently reads
> Write your article, run npm run meta, commit your changes locally, and push your new branch to GitHub with the command `git push origin <new-branch-name>`

It should read
> Write your article, commit your changes locally, and push your new branch to GitHub with the command 'git push origin <new-branch-name>`

**Comment by emarkchrome** [comment]
I made the edit and tried to submit a PR. I hope I followed all the conventions.

**Comment by Bouncey** [comment]
closed via #130
