### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#148]
Create a good index.md file for the root directory (that shows when you navigate to Guides directly.

This file should be situated in  `src/pages/ `.

**Comment by vikramnr** [comment]
@Bouncey  Can I give it try?

**Comment by Bouncey** [comment]
Go for it @vikramnr 👍

**Comment by vikramnr** [comment]
@Bouncey Any suggestion on what it should contain?

**Comment by Bouncey** [comment]
>  Create a good index.md file for the root article directory (that shows when you navigate to Guides directly.

It should contain a welcome to the guide and a suggestion to search for what they would like to know
