### ISSUE TITLE
Performance issues while running locally.

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/guides#156]
Sometimes while running the repo locally, it gets stuck at the point where it reads `Bootstrap finished`.

**Comment by Bouncey** [comment]
@invinciblycool there is a breaking change in the gatsby ecosystem that causes the issue you describe.

For now, remove the `^` infront of the package versions numbers like below, you should then be able to run the guide locally.

I have a PR in currently that will make this change by default

```
    "gatsby": "1.6.6",
    "gatsby-link": "1.6.5",
    "gatsby-plugin-react-helmet": "1.0.1",
    "gatsby-plugin-sharp": "1.6.0",
    "gatsby-plugin-sitemap": "1.2.0",
    "gatsby-remark-copy-linked-files": "1.5.0",
    "gatsby-remark-images": "1.5.0",
    "gatsby-remark-prismjs": "1.2.0",
    "gatsby-remark-responsive-iframe": "1.4.1",
    "gatsby-remark-smartypants": "1.4.1",
    "gatsby-source-filesystem": "1.4.1",
    "gatsby-transformer-remark": "1.6.3",
```
