### ISSUE TITLE
Webhook that adds new guide articles to Elastic Search

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#16]

**Comment by Bouncey** [comment]
This issue will be transferred to the CMS repo once created

**Comment by systimotic** [comment]
@Bouncey Has this been completed in https://github.com/freeCodeCamp/search/pull/34?

**Comment by Bouncey** [comment]
We still need to add it to this repo's settings

**Comment by systimotic** [comment]
Related: #387

**Comment by Bouncey** [comment]
closed in favour of #387
