### ISSUE TITLE
Best Practices Guide

### ISSUE THREAD

**Issue by jjpatel361** [freeCodeCamp/guides#1996]
I am interested in writing best practices for REST API.  Does it go in `software-engineering` or `software-engineering/design-patterns`?

**Comment by amandeepmittal** [comment]
IMO it could do better in `design-patterns`.

**Comment by davcri** [comment]
Best practices are not design patters. When I speak about design patterns I think something like _singleton_, _observer_, and other Gangs of Four design patterns.  

@jjpatel361 It's hard to tell, it depends on the content of the article.

**Comment by amandeepmittal** [comment]
@jjpatel361 Instead of best practices, why don't you go for guide of REST Apis irrespective of programming languages.

**Comment by jjpatel361** [comment]
Thanks, folks. Ended up creating a separate folder `rest-api`. This is my last commit for **hacktoberfest**.
Closing this issue now!
