### ISSUE TITLE
Adding audio capabilities to the Guides project?

### ISSUE THREAD

**Issue by evaristoc** [freeCodeCamp/guides#21]
A discussion in the CT suggested the potential of associating audio content to the guides.

This thread opens a discussion about the desirability and feasibility of this proposition and if approved then start designing the corresponding road map.

@QuincyLarson @Bouncey @raisedadead @dhcodes

**Comment by evaristoc** [comment]
This is a comment by @dhcodes:
https://gitter.im/FreeCodeCamp/CoreTeam?at=59400438cf9c13503c80c95e

**Comment by QuincyLarson** [comment]
In my opinion this is a "nice to have" and not something we need to worry about at this point. If necessary, we could always embed YouTube or Sound Cloud files.
