### ISSUE TITLE
Promise is not supported by IE 11

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#217]
@QuincyLarson From which browser version are we supporting?

Currently the search will not work in IE11. 

We could:

- Add a polyfill for Promise's
- Refactor to not use Promise's
- Inform the user that the search page does not support their browser after doing a `'Promise' in window` check, and suggest they try chrome/firefox/edge

Personally I am not a fan of shipping polyfill to everyone regardless, and I like Promise's. So I would vote for the 'No support search page' and suggestion of upgrading.

**Comment by QuincyLarson** [comment]
@Bouncey If you could replace the search with a note "Search doesn't work in IE" or something like that is fine.
