### ISSUE TITLE
Links not working on Guide to Back-end Projects!

### ISSUE THREAD

**Issue by amandeepmittal** [freeCodeCamp/guides#2170]
Page: `https://guide.freecodecamp.org/miscellaneous/guides-to-back-end-projects`
![screen shot 2017-10-20 at 5 38 59 pm 2](https://user-images.githubusercontent.com/10234615/31820171-afce654c-b5bd-11e7-886d-f97ad4ee8e17.png)

**Comment by srk97** [comment]
657ed99078fcfd7db20e7579b850fcd24c1a83bc

**Comment by srk97** [comment]
657ed99078fcfd7db20e7579b850fcd24c1a83bc

**Comment by srk97** [comment]
Links to Socket I/O and JS-IsLoggedInAsync could not be found.

**Comment by srk97** [comment]
#2372

**Comment by amandeepmittal** [comment]
My quesrion is do the links exist or not. If not we can close this issue and don't bother.

**Comment by srk97** [comment]
@amandeepmittal look at the PR. There are links to all the articles except JS-IsLoggedInAsync as I said before.

**Comment by amandeepmittal** [comment]
@srk97 Okay. That sums it up. Earlier it was not clear to me about what you just said. Let's close this issue if the PR is already in the process.
