### ISSUE TITLE
Update contibuting GIF in README

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#219]
The GIF in the readme still shows the `guide-articles` repo.

This needs to be update for this repo

**Comment by shovanch** [comment]
@Bouncey Can I take this? This would be my first open source contribution.

**Comment by Bouncey** [comment]
Absolutely @shovanch Thanks :+1:

**Comment by shovanch** [comment]
@Bouncey Just a question. Would it be ok to host the gif using imgur?

**Comment by Bouncey** [comment]
Sure
