### ISSUE TITLE
Flicker while search results load

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#230]
No gif, because the flicker is probably too fast to properly capture it. Instead, I have
### Steps to reproduce
1. Search for something, like "Beau Carnes"
2. Add or remove one character

You'll notice that you immediately get the expected flicker of the skeleton and then to the actual results. This is expected. The problem happens right after that. It shows a flicker of the skeleton again, then back to the results. This double flicker is quite annoying and unexpected.

This problem is most noticeable on repeated searches with fast connection. If the search takes long enough, there will only be a single (expected) flicker.

### Possible causes
I'm not certain of the actual cause, but here's what I do know:
- It's not the event. As far as I can tell, `onChange` only fires once per change, and `onSubmit` doesn't influence anything.
- Commenting out line 21 in `searchEpic.js` did appear to solve the problem.
https://github.com/freeCodeCamp/guides/blob/27f2603c36383b0d06b90f628950a22d017cabdc/src/layouts/components/search/redux/searchEpic.js#L19-L22

Furthermore, we might want to completely disable the skeleton for repeated searches and only show it for the first one. It would eliminate the expected flicker.
It would show the skeleton from the first key press, and it would show a 'no results' message after a timeout if the user doesn't continue typing. If the first results have loaded and the user searches again while still on the search page, the skeleton isn't shown. This would probably be more comfortable than the constant flicker, and more consistent with other typeahead experiences.

**Comment by Bouncey** [comment]
> The problem happens right after that. It shows a flicker of the skeleton again, then back to the results. This double flicker is quite annoying and unexpected.

Is it as if the results page updates and then fetches and updates again?

If is it is indeed an issue with `source$.throttle().debounce()`. I was trying not to spam the server on every keystroke,  but keep it relatively speedy. The throttle/debounce is a solution to ensure I receive the first and last event. I can't remember which one it is, but one chops off the first and the other chops off the last. 

We could add some additional logic that doesn't clear the results array unless the input is below 3 chars. That should stop the flicker, but keep the speed of the search.

**Comment by systimotic** [comment]
> Is it as if the results page updates and then fetches and updates again?

Yes, that's exactly what's happening.

> We could add some additional logic that doesn't clear the results array unless the input is below 3 chars. That should stop the flicker, but keep the speed of the search.

Looking at the code, we're not clearing the array. The flicker is caused by `isSearching`
https://github.com/freeCodeCamp/guides/blob/27f2603c36383b0d06b90f628950a22d017cabdc/src/pages/search/Search.jsx#L47-L52

I read up on `throttle` and `debounce` a bit. If `x` is the amount of time specified, `throttle` will emit the first value it gets, then nothing for `x`. It will only emit a value again after `x` has passed. `debounce` will wait `x`, then emit the most recent value. It's clear to me now why having both is good for performance (both not overloading and starting fast), and why it runs twice.

I was playing around with this, and I think I may have found a solution that works. It stores the last query, and if it's equal to the new one, it doesn't search. Can you take a look at this and see if it's alright, or if there's a better way?
https://github.com/systimotic/guides/commit/e8f987c13be68b71318d9b068e308913d30d2c07

I also did a quick comment to see what it would look like without the ResultsSkeleton. While I really like the look of the skeleton, the experience on my laptop is much nicer without it. I'm worried about slower connections and devices though (older smartphones on a dodgy 3G, for example). From my testing using Chrome's emulation, neither solution is great on such devices. The skeleton doesn't really seem to improve the experience in this case either. If we decide that we want to remove the skeleton, I'll go through and remove it properly.
