### ISSUE TITLE
Links to challenges in search broken

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#231]
The links to the freeCodeCamp challenges in the search all result in 404 errors.

The data and links appear to be referring to beta challenges, but the links all link to the production `freecodecamp.com`.

The full URL's are taken directly from the search API, so I believe this will have to be resolved there too.

**Comment by systimotic** [comment]
Looks like this is handled [here](https://github.com/freeCodeCamp/search/blob/ace7b15276ec2170045d00b435ee74031fc3e467/init/challenges/index.js#L70)

Using [this article from GitHub](https://help.github.com/articles/support-for-subversion-clients/#switching-between-branches) and [this method from node-svn-ultimate](https://www.npmjs.com/package/node-svn-ultimate#commands.switch), we might be able to figure this out.

**Comment by Bouncey** [comment]
Oops... still valid

**Comment by systimotic** [comment]
Awesome work @Bouncey!
