### ISSUE TITLE
New Section

### ISSUE THREAD

**Issue by blakeathomas** [freeCodeCamp/guides#2319]
I was thinking would it be helpful to open an IDE section. It could contain key features, snapshots so that readers could see the layout w/o installing it and other things. If so I would be willing to create the folder and a few different pages w/ stubs.

**Comment by Glazy** [comment]
Hey @blakeathomas, I agree it would be really helpful to have a section on this.

Having a consistent and well formatted set of features, screenshots and quirks for every mainstream IDE would be great.

**Comment by blakeathomas** [comment]
I just opened PR #4387. Hopefully it's helpful and gets merged
