### ISSUE TITLE
Update document.title for the search page

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#236]
This can be accomplished with `react-helmet`

See [Article.jsx](https://github.com/freeCodeCamp/guides/blob/master/src/templates/Article.jsx#L17) for a previous implementation.

**Comment by williamsb** [comment]
What should the title be updated as? Also the Article.jsx example had a link, are we including the link for the search page?

**Comment by Bouncey** [comment]
@williamsb thanks for the interest

`Search | freeCodeCamp Guide` should do fine.

We don't need the canonical link for the search page.

**Comment by williamsb** [comment]
@Bouncey I can take this.

**Comment by Bouncey** [comment]
:+1:
