### ISSUE TITLE
git clone url_of_repository not showing

### ISSUE THREAD

**Issue by davycheung** [freeCodeCamp/guides#239]
On the git clone guide: https://guide.freecodecamp.org/articles/git/git-clone

The following lines are not rendering the git clone parameters on the site:
`git clone <url of repository>`
`git clone <url of repository> <name of directory on computer>`

Instead both lines are just displaying:
`git clone`

**Comment by texas2010** [comment]
Yeah. `<url of repository>` is hiding. 
![screen shot 2017-09-04 at 10 24 45 am](https://user-images.githubusercontent.com/9701609/30032404-5ca8fed0-915b-11e7-8332-0f68996ba119.png)

**Comment by Bouncey** [comment]
That's strange. I guess they need to be either escaped or replaced with HTML entities `&lt; &gt;`

**Comment by williamsb** [comment]
I can take this!
