### ISSUE TITLE
Update Python documentation reference in Converting Integer to String in Python

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/guides#265]
[This line](https://github.com/freeCodeCamp/guides/blob/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/python/converting-integer-to-string-in-python/index.md#more-information) needs to be updated to the Python 3 documentation, as the code used in the examples are Python 3.

[This](https://docs.python.org/3/library/stdtypes.html#str) should be the correct link.

**Comment by shovanch** [comment]
Would love to contribute. Can I take this?

**Comment by invinciblycool** [comment]
Sorry but I have already opened a PR,  you could try [this](https://github.com/freeCodeCamp/guides/issues/266)

**Comment by shovanch** [comment]
@invinciblycool Sure.
