### ISSUE TITLE
Folder needs to be renamed as python-hex-function

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/guides#266]
Not sure why [this](https://github.com/freeCodeCamp/guides/tree/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/python/python-hexx-function) folder is named with two x's. The title in the YAML header should also be changed to have only one "x" in the title.

**Comment by shovanch** [comment]
Hello, Is anyone working this. If not can I take this?
