### ISSUE TITLE
Remove extra `x` from python folders

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#270]
Inspired by #266, I took a look at what might have caused this issue.
I found a three more directories with the same problem:
- [python-absx-function](https://github.com/freeCodeCamp/guides/tree/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/python/python-absx-function)
- [python-boolx-function](https://github.com/freeCodeCamp/guides/tree/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/python/python-boolx-function)
- [python-lenx-function](https://github.com/freeCodeCamp/guides/tree/18b9668e84be5715267eaf7efecfe9d1454ea5ec/src/pages/python/python-lenx-function)

I [searched for python articles on the forum](https://forum.freecodecamp.org/search?q=python%20category%3A373) and found the source of this issue there. The original titles are `name(x)`. In the importing process, the special characters `()` were removed from the title, but the `x` was left.

The `x` will need to be removed from the title and the folder name, the same way it was done in https://github.com/freeCodeCamp/guides/pull/269

**Comment by shovanch** [comment]
@systimotic Can I take this?

**Comment by systimotic** [comment]
@shovanch For sure!

**Comment by Bouncey** [comment]
Closed via #271

**Comment by systimotic** [comment]
Wow, that was fast! Thanks guys 👍
