### ISSUE TITLE
Insertion sort code is not displaying properly

### ISSUE THREAD

**Issue by blulion** [freeCodeCamp/guides#2736]
I've added an article about insertion sort with algorithm and code example in Swift language. But the code example is not displaying the complete code. `while` conditions were missing. when i try to edit the code, i could see the original code. I think there is some issue with formatting. How can i correct it.

https://guide.freecodecamp.org/algorithms/sorting-algorithms/insertion-sort

https://github.com/blulion/guides/blob/algorithms/sorting-algorithms/insertion-sort/src/pages/algorithms/sorting-algorithms/insertion-sort/index.md

**Comment by johnkennedy9147** [comment]
@blulion I think its because in your code example you haven't specified a language so things like `<INT>` and `<array.count  ... while (i >`are being treated as html tags and not displayed.

Changing line 100 to:

```
```swift
```

should fix.

**Comment by blulion** [comment]
@johnkennedy9147: Thank you.
