### ISSUE TITLE
Put an emphasis on good PR naming.

### ISSUE THREAD

**Issue by Glazy** [freeCodeCamp/guides#2742]
There are too many PRs named `Update index.md` and it is getting a little bit out of control. For someone who is looking to contribute there is absolutely no way to tell whether a PR is already in the works and it can be off-putting.

I think the solution to this would be to just auto-close any that don't make sense or have just been left as the default.

I did notice an issue already open about this subject (#1853) and I think having something in the guidelines is a great idea but sadly not everyone is going to follow the guidelines. I think by automatically discounting PRs that are named in the default way we have a great filter for PRs that aren't great quality.

This also incentivizes good PR naming as someone knows if they want their PR looking at it has to be sensibly named.

What do you think?

**Comment by davcri** [comment]
Can we discuss this in #1853 ?

**Comment by Glazy** [comment]
Sure thing @davcri!
