### ISSUE TITLE
HTML rendering inside Code Examples

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#275]
So while looking over the new installation of freeCodeCamp Guides I noticed HTML was running inside the code example which breaks the ability to show users how to use various frameworks. Is anyone else experiencing this issue?
<img width="1280" alt="screen shot 2017-09-17 at 12 18 48 pm" src="https://user-images.githubusercontent.com/8227641/30522706-66f8a47a-9ba2-11e7-8911-78c86fdbc0be.png">

**Comment by MrAsrani1312** [comment]
Yup , like #233 . I'm facing this problem too

**Comment by systimotic** [comment]
Thanks for reporting @nsuchy! This was fixed with #267.
