### ISSUE TITLE
Incorrect link in python2vspython3.

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/guides#280]
Found a link in the [python2vspython3 article](https://github.com/freeCodeCamp/guides/blob/master/src/pages/python/python-2-vs-python-3/index.md), which points to 404 page.

This is the incorrect link http://spartanideas.msu.edu/2014/06/01/the-key-differences-between-python-2-7-x-and-python-3-x-with-examples/

**Comment by erictleung** [comment]
Thanks for catching this. A similar link that can be used in place of this might be [this](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html).

**Comment by shovanch** [comment]
Can I take this?

**Comment by Bouncey** [comment]
@shovanch if a PR isn't raised feel free to open one. You don't need permission, all contributions are welcome! 👍

**Comment by shovanch** [comment]
@Bouncey OK. Got it.

**Comment by HKuz** [comment]
Closed via #286
