### ISSUE TITLE
Remove markdown symbols from search results

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#289]
Currently search results show markdown like this:

![](https://www.evernote.com/l/Ar-nKXRglXROgZwj-pp-RasddJ8gDPbijncB/image.png)

We can probably remove the title from the text completely. It's possible an article could start with a table or other markdown syntax, but we can cross that bridge when we get there.

**Comment by systimotic** [comment]
Should this be handled here, or should the search API also have a version that doesn't contain Markdown? /cc @Bouncey

**Comment by Bouncey** [comment]
I think I would prefer sending the raw data from the api like we are and just filtering the markdown away in the Results component
