### ISSUE TITLE
Fix navigations for better accessibility

### ISSUE THREAD

**Issue by sanatankc** [freeCodeCamp/guides#2931]
That's how header and navbar are for now
![now](https://user-images.githubusercontent.com/20373641/31859321-dcfb2b16-b727-11e7-8982-cdc469fedae8.gif)
That's how I think they ideally should be
![ideal](https://user-images.githubusercontent.com/20373641/31859339-006162aa-b728-11e7-81b1-8cba3d297f4b.gif)

I would love to help in this.

**Comment by Ankk98** [comment]
i would like to help

**Comment by Ankk98** [comment]
if we change the .navbar properties and add fixed position attribute, we face the issue of div on wrong containers.
They are overlapping.
div of navbar and other part of page should be under the same div according to me.
But i guess this is react js and i am not familiar with it :/ .

**Comment by paolomangiadev** [comment]
working on this :)

**Comment by systimotic** [comment]
Thanks a lot for reporting and fixing this @Ankk98 @paolomangiadev! We already have an open PR (https://github.com/freeCodeCamp/guides/pull/338) and issue about this, so I'm closing this as a duplicate.

Happy coding!
