### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/guides#328]
If the navmenu isn't going to be fixed to the side, we should include a 'return to top' button/icon. Or we should make the navmenu fixed to the side of the screen so even when we scroll down on a long documentation page we can navigate to the next page easier.

This issue is open for feedback, I'm also happy to work on the CSS/JS required to make it happen.

**Comment by Bouncey** [comment]
A fixed SideNav sounds great :+1: 

Just so I'm certain, we are talking about a sticky side nav that remains in place when scrolling through an article?

**Comment by Ethan-Arrowood** [comment]
Yep :+1:

**Comment by Ethan-Arrowood** [comment]
I'll roll something out today.
