### ISSUE TITLE
Refactor _createNavData and SideNav to avoid dashedName collisions

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/guides#337]
I'm currently taking a course on Data Structures and I think a section on this subject would be very useful. Content could include: Bags, Dictionaries, Sets, Trees, etc. 
I'm currently implementing these structures using Java; however, we could provide multiple implementations in different languages such as Java, Python, C++, and even JavaScript.

**Comment by systimotic** [comment]
Hi @Ethan-Arrowood!

We do have a section on data structures: [GitHub](https://github.com/freeCodeCamp/guides/tree/master/src/pages/computer-science/data-structures) I'm looking forward to seeing your contributions to it! Feel free to add new articles there too.

An issue I'm seeing with this is that this section doesn't show up in the SideNav. [A direct link](https://guide.freecodecamp.org/computer-science/data-structures/trees/) does work, but it still doesn't show up in the nav. /cc @Bouncey

**Comment by Bouncey** [comment]
We have another naming conflict, `data-structures` can be found in both `computer-science` and `python`. I'm sure it wont be long until we get them for C, C++, Java, JavaScript, Clojure and every other language. 

At the minute, sorting of the side nav is done through `dashedName`'s, and this is where we got the collision with `Math` from prviously. 

We should probably restructure both `_createNavData` and `SideNav` to sort by `path`, as at least they should be unique

**Comment by Ethan-Arrowood** [comment]
I'll take a stab at this @Bouncey. I've been working with a lot of parsing algorithms recently so I think I should be able to figure this out. Will update by end of the day :+1:

**Comment by Ethan-Arrowood** [comment]
What I've gathered so far is that the _createNavData does add 'data-structures' to the 'computer-science' page: 
<img width="247" alt="screen shot 2017-09-24 at 6 28 10 pm" src="https://user-images.githubusercontent.com/16144158/30787433-30a70fce-a156-11e7-89be-1b411989f81f.png">
However, it (_createNavData) does not create a distinct 'data-structures' page with a path of 'computer-science/data-structures'. It DOES create one for python. There are also subpages for the 'computer-science/data-structures' such as 'queue' and 'stack'. This means the **bug exists in the _createNavData file**. @Bouncey let me know if I'm on the right track. I'll continue to update as I attempt to solve this bug.

**Comment by Bouncey** [comment]
@Ethan-Arrowood the bug is that `dashedName` is not a unique identifier. All the needs to happen with `_createNavData` and `SideNav.jsx`is where-ever we are using `dashedName` to find a child/parent, we should use paths instead

**Comment by Ethan-Arrowood** [comment]
I'm stumped on this one. @Bouncey feel free to try to fix this yourself; you can probably figure it out faster than I can.
