### ISSUE TITLE
Syntax highlighting for code snippets

### ISSUE THREAD

**Issue by vancanhuit** [freeCodeCamp/guides#362]
As I browse some articles, I see some code snippets isn't highlighted correctly. So I hope authors should re-check and apply proper syntax highlighting for it.

**Comment by Bouncey** [comment]
@vancanhuit A lot of articles were ported over from the [forum](https://forum.freecodecamp.org) and were written a while a go.

If you spot any articles without syntax highlighting, if you (or anyone) could raise either an issue or a PR against that article, it would be greatly appreciated :+1:

**Comment by vancanhuit** [comment]
@Bouncey I will try to do this.
