### ISSUE TITLE
Search results are not updated with new content

### ISSUE THREAD

**Issue by chiragbhansali** [freeCodeCamp/guides#387]
If you search for already published articles (like css cursors or markdown), the result will show but it is being labelled as a stub. Also, the search is returning different articles for if I type 'cursor' or 'cursors'(the result for 'cursor' is actually a broken link).

**Comment by Bouncey** [comment]
Thank you for reminding me about the webhook! @QuincyLarson I will send you the webhook for guides later today

**Comment by systimotic** [comment]
@Bouncey 🔔 How is this going?

**Comment by Bouncey** [comment]
@QuincyLarson has the details, just waiting on confirmation that the hook has been added

**Comment by Bouncey** [comment]
This is now completed :tada:

**Comment by systimotic** [comment]
Awesome!

**Comment by QuincyLarson** [comment]
Awesome! This is huge! Thanks, @Bouncey
