### ISSUE TITLE
When I visit the root path, I should see the contents of the /docs folder - not a landing page.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#4]

**Comment by Bouncey** [comment]
@QuincyLarson would a redirect to`/docs` be ok?

The app structure at the moment requires the guide pages to be in `/docs`

**Comment by Bouncey** [comment]
Without a redirect, this will require the likes of a huge mono-template in which react is in reality doing the job of `gatsby`. 

We can rename the `docs` dir, but removing it means that gatsby just a dev and build tool, not a static site generator

**Comment by QuincyLarson** [comment]
@bouncey sorry I didn't close this issue sooner. I thought I mentioned during the meeting that we can specify /docs as the build directory in Netlify so that we don't need to actually change Gatsby's code.
