### ISSUE TITLE
All URLs should be fully lower-case

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#40]
A lot of the folders are currently capitalized. We should probably lowercase these. 

I noticed that on Amazon, all search results in their autocomplete are lowercase - even for proper nouns. I think we could do the same.

The only place where capitalization might be important outside of the individual article itself is in the side navigation. So we may need to figure out a way to make this happen.

If we can't figure this out, we may just want to leave the side navigation all lowercase for now.

**Comment by Bouncey** [comment]
The side nav can cope with lowercase folder names. This should be taken care of in the `guide-articles` repo.

**Comment by Bouncey** [comment]
closed via #47
