### ISSUE TITLE
Fix header

### ISSUE THREAD

**Issue by svcastaneda** [freeCodeCamp/guides#4035]
When a window gets small enough, a top and bottom border appear on the search bar. It also has no padding, which makes it seem cramped.

![image](https://user-images.githubusercontent.com/6743763/31936657-cebf74b6-b877-11e7-8b89-dda5515bc9fb.png)

![image](https://user-images.githubusercontent.com/6743763/31936716-ff00af6e-b877-11e7-8b08-238671dd7e23.png)

**Comment by systimotic** [comment]
Thanks for reporting this @svcastaneda! We already have an open PR (https://github.com/freeCodeCamp/guides/pull/229) and issue that address this, so I'm closing this as a duplicate.

Happy coding!
