### ISSUE TITLE
Articles have duplicate stubs

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/guides#410]
Seeing a number of instances where an article has been added but the placeholder stub remains.

Some examples under Javascript - comparison operators, for loop  and for in loop
![stubs](https://user-images.githubusercontent.com/26827682/30817768-b140f74c-a211-11e7-9316-e488930ac660.jpg)

**Comment by Bouncey** [comment]
I agree this needs cleaned up. Most of the content here was ported over from the forum, so I'm not surprised to see duplicate articles as it was done programmatically

QA'ing 2000+ articles in one go would have been impossible for the three of us at that time

**Comment by johnkennedy9147** [comment]
I can do this then.

What would be easier for you?

Individual PR for each to be removed.
Batches of a few at a time.
Everything to be deleted from a section eg JavaScript one day, HTML another...
All at once when I get through it all.

**Comment by johnkennedy9147** [comment]
@Bouncey pr #459 #482 (already merged) and #586 (currently pending) combined should resolve this issue

**Comment by systimotic** [comment]
@johnkennedy9147 I think we caught all of these. Can you do a final check and close this if it is indeed resolved?

**Comment by johnkennedy9147** [comment]
New ones likely to be created as we progress, so I'll close this issue and periodically check and resolve any others I find.
