### ISSUE TITLE
Javascript/Tutorials contains non Javascript related stubs and articles

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/guides#412]
Many of the stubs and articles listed here related to HTML or CSS rather than JavaScript.

I would suggest the ideal solution is that there is a top level Tutorials section (containing all tutorials), and a Tutorials section in each section for which there are tutorials containing only those relevant to that area, eg HTML/ Tutorials, CSS/ Tutorials...

This would improve discoverability of relevant tutorial  articles for users.

**Comment by Bouncey** [comment]
This could be related to #337

**Comment by johnkennedy9147** [comment]
Yeah, looking in the source code html/tutorials, css/tutorials and javascript/tutorials all seem to have correct content but in side nav they all show up under javascript/tutorials and no tutorials section appears under html or css

**Comment by systimotic** [comment]
😞 That's an annoying issue. Thanks for reporting this @johnkennedy9147, I'll close this in favor of #337. Happy coding!
