### ISSUE TITLE
Add CSS pre-processor

### ISSUE THREAD

**Issue by m-henderson** [freeCodeCamp/guides#415]
Hey Contributors! I am working on implementing night mode for guides, but to make this easier, I need [LESS](http://lesscss.org/). What are your thoughts on adding this to the application? Are you cool with it ?

**Comment by Bouncey** [comment]
LESS || SASS || Stylus 👍

**Comment by m-henderson** [comment]
Removed less and added sass https://github.com/freeCodeCamp/guides/pull/431
