### ISSUE TITLE
Article on Functional Programming

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#433]
Since we mention Functional Programming in [the Medium article](https://medium.freecodecamp.org/heres-a-new-way-to-learn-coding-tools-and-concepts-right-when-you-need-them-ee82d15c576d), we should create an article on Functional Programming in case people search for it. 

Would anyone be interested in writing it? It could go in the Software Engineering folder.

**Comment by chiragbhansali** [comment]
#441
