### ISSUE TITLE
What about using ES6 in JavaScript guide?

### ISSUE THREAD

**Issue by mfaheemakhtar** [freeCodeCamp/guides#437]
I think, it would be much better to use ES6 or JavaScript + ES6 in JS section. New comers must know and learn about ES6, its benefits and features.

I'm also a newbie but would love to contribute in JS.

**Comment by vancanhuit** [comment]
I think so too. We need to place ES6 articles into a separate topic in JavaScript for easy referencing.

**Comment by systimotic** [comment]
I'd love to see some articles about ES6 in the Guide!

**Comment by johnkennedy9147** [comment]
closing issue as ES6 section has been created and several articles added
