### ISSUE TITLE
Javascript > Tutorials > Page Redirects Using JavaScript

### ISSUE THREAD

**Issue by OmoleOO** [freeCodeCamp/guides#450]
While viewing the page, javascript > tutorial > page redirects using javascript, I get redirected to "www.yoururl.com".

**Comment by systimotic** [comment]
Sorry about that @OmoleOO! Interestingly, I only get redirected in Chrome, not in Firefox. Regardless, the issue exists because we have an issue where HTML in a code block is run unless it's inside an HTML code block. I'm opening a pull request to fix the issue in this specific case.

**Comment by OmoleOO** [comment]
Great job, guys!

**Comment by systimotic** [comment]
Thank you for reporting this @OmoleOO! If nobody tells us about it, we can't fix it 😄
