### ISSUE TITLE
Add Terminal/Command Line Article

### ISSUE THREAD

**Issue by jromest** [freeCodeCamp/guides#4517]
Can we add article about terminal or command line and its basic usage?

**Comment by Ethan-Arrowood** [comment]
If you would like to feel free to do so and submit a PR!

**Comment by Bentley912** [comment]
Just created a pull request for this

**Comment by Ethan-Arrowood** [comment]
Can you send the link for tracking please

**Comment by Bentley912** [comment]
What link are you talking about?

**Comment by Ethan-Arrowood** [comment]
Of your pull request. When it is eventually merged we will want to close this issue.

**Comment by Bentley912** [comment]
https://github.com/freeCodeCamp/guides/pull/7921

**Comment by amandeepmittal** [comment]
Can we close this issue now? The PR is already merged.
