### ISSUE TITLE
Search results showing articles that are no longer available

### ISSUE THREAD

**Issue by davidkwan95** [freeCodeCamp/guides#454]
When searching, I've found a lot of links that lead to 404. I think removed articles should not be included in the search results.

**Comment by systimotic** [comment]
Hi @davidkwan95! Thanks for reporting this. 

It looks like this is caused by the same issue as #387, so I'm closing this as a duplicate. If the issue persists after #378 is closed, please reopen this with some examples of search queries that have broken links.

Happy coding!
