### ISSUE TITLE
Isloggedinasync article should be removed

### ISSUE THREAD

**Issue by davidkwan95** [freeCodeCamp/guides#455]
I don't think this article https://guide.freecodecamp.org/javascript/isloggedinasync belong in the javascript section because it is not a native javascript function. My suggestion is, making an article about asynchronous JavaScript and put that isLoggedInAsync as an example.

**Comment by systimotic** [comment]
Thanks for reporting this @davidkwan95!

It looks like this article is related to Angular. We don't have a section on that yet, but it's definitely not in the correct section now. There are some Angular articles in the miscellaneous section, but I think this article should be removed.

**Comment by johnkennedy9147** [comment]
I was thinking it would be good to have a section within JavaScript for Libraries & Frameworks, then in that section sub-sections for those we have articles pertaining to. The whole JQuery section for example could nest under that.

**Comment by systimotic** [comment]
@johnkennedy9147 That would probably be a good idea to do eventually, but this article specifically still won't be useful there. It appears to be referring to something that we don't have the context of.

**Comment by dhanushuUzumaki** [comment]
Created a PR for this #664 .
