### ISSUE TITLE
Searching for 'functional programming' does not show the basic Functional Programming article

### ISSUE THREAD

**Issue by clearyusc** [freeCodeCamp/guides#456]
Instead, it shows a bunch of other articles that are related to functional programming, but you would expect it to take you to the main article, https://guide.freecodecamp.org/software-engineering/functional-programming, and not tangentially related or more complex articles.  

This is especially important because this is the example used in the freeCodeCamp blog announcement!

**Comment by enguerran** [comment]
That is very true, here is a screenshot of the results I had:

![](https://i.imgur.com/5TMB3ne.png)

For other «_search engines_», I guess we should wait for the website to be indexed:

![](https://i.imgur.com/tn7xk5B.png)

![](https://i.imgur.com/nA9iDCy.png)

**Comment by danedavid** [comment]
I think the article on functional programming got merged just today... now we may be able to fix this

**Comment by systimotic** [comment]
Hi everyone! Thanks for reporting and looking into this.

I agree that this is an important issue.
As mentioned, the article was only merged very recently. The database we use for searching is not updated automatically yet. We're addressing that in #387, so I'm closing this as a duplicate.

Happy coding!
