### ISSUE TITLE
Get nav bar logo to look like the logo on  https://www.freecodecamp.com/donate/ with similar size logo and placement.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#5]

**Comment by kuriakinzeng** [comment]
Completed

**Comment by Bouncey** [comment]
@kuriakinzeng This needs done again, sorry

**Comment by kuriakinzeng** [comment]
What happened?

**Comment by Bouncey** [comment]
I replaced the project with a version that is compatible with the latest stable release. I forgot to copy over your changes, sorry

**Comment by QuincyLarson** [comment]
@kuriakinzeng what we'd really like to do is create a component that we can re-use on all the guide pages and on our non-guide pages (our challenge pages), which includes basic navigation and a search box that pulls results from ElasticSearch. @Bouncey is working on making this a reality.

**Comment by kuriakinzeng** [comment]
Yup, I can do this again. I plan to remove the `react-responsive-grid` package because it's very limited, and use bootstrap. Does this sound good?

**Comment by kuriakinzeng** [comment]
Please take a look at the styling I have so far: 
https://codepen.io/kuriakin/full/OgRexK/

**Comment by Bouncey** [comment]
Looking great @kuriakinzeng, I like how clean it looks. 

What I got from our talks is that search is going to be a major feature of the guides site, so maybe something that is always visible on the page would be better. Maybe it can expand in width on focus so as not to overly dominate the UI?

Also, try coding the pen with `react` and `react-bootstrap`. This should give you a greater feel for the lib that we will be using.

The `react-bootstrap` docs [here](https://react-bootstrap.github.io/getting-started.html#commonjs) confirm that there is no dependency on `jQuery`. Just for your information.

You can use `https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.min.js` in your external scripts to import the lib into codepen.

**Comment by kuriakinzeng** [comment]
Yup, I just needed a quick and dirty way to try the styles. Will implement it in react and not use jquery.    
  
  
  

  
Regarding the search bar, how do we want it on mobile? Hide it? Or something like this:   https://codepen.io/kuriakin/full/BZLbdB
  
  
  

  
  
>

**Comment by Bouncey** [comment]
I think stacking the logo on top of the search bar would be best on mobile.

**Comment by kuriakinzeng** [comment]
Stacking?    
  
  
  
  
  

  
  
>

**Comment by Bouncey** [comment]
Sorry, on top of each other, like this https://codepen.io/Bouncey/pen/gRLoYO

**Comment by QuincyLarson** [comment]
@kuriakinzeng I think your design is off to a good start. Our style is to not use icons in the navbar - instead to spell things out. This is much clearer than icons, and less likely to be misunderstood. So you might put "Contribute" and that would link to the contribution guide - which could then link to specific issues.

**Comment by QuincyLarson** [comment]
@kuriakinzeng @bouncey one thing I noticed is on Facebook, it has a search button (using a magnifying glass) that - when you click it if you haven't typed anything - shows popular or recent search queries. I think we should have a search button even though we'll have real-time search to reinforce that it is indeed a search box.

I agree with @bouncey that we should always show the search bar, even on mobile (it can be stacked), and the header should not be fixed or it will take up a lot of room on the mobile display.

**Comment by kuriakinzeng** [comment]
I originally designed it to be like Facebook's, with no submit button and fixed to the top. I   have modified it to stack like Bouncey suggested. So now, the modifications left to be done are adding   a submit button and making the header not fixed.
  
  
  
 The styling doesn't quite work on my iPhone for some reason. So I need to fix that too.
  

  
 Will next weekend be too late to finish this styling? I have spent 15 hours this week on styling (I'm not very good with css unfortunately) and won't have the time to work on this until late next week.
  

  
  
  
>

**Comment by QuincyLarson** [comment]
@kuriakinzeng Awesome! No rush - I think @bouncey getting the structure working properly and getting ElasticSearch box working within Gatsby are the critical path. And I'll be around all weekend to help with these steps.
