### ISSUE TITLE
Add Vim Section?

### ISSUE THREAD

**Issue by beigebrucewayne** [freeCodeCamp/guides#503]
Would adding a Vim section make sense? If so, I'd be down to help contribute to it's development.

**Comment by jamesjpk123** [comment]
Vim section is being added in PR #514, if it goes through.

**Comment by beigebrucewayne** [comment]
I'm the same guy. Decided to just add it myself...lol.

**Comment by jamesjpk123** [comment]
Oh didn't realize @beigebrucewayne lol.

**Comment by HKuz** [comment]
@beigebrucewayne - looks like you've got a few votes of approval on your suggestion, and I think having a Vim section would be a welcome add (especially that exit article... 🤣). In general, anything development, design, or data science-related is fair game here, and folks would certainly appreciate a quick reference for the Vim keyboard shortcuts. I'll go QA your PR to get it merged, so the section is in place for future articles 👍

**Comment by HKuz** [comment]
Closing this issue as it was addressed in #514. Thanks everyone!
