### ISSUE TITLE
Stub for Python: Comprehensions

### ISSUE THREAD

**Issue by pszalanski** [freeCodeCamp/guides#526]
Python has a powerful feature: Comprehensions. They make it possible to write a for loop in one line, e.g.

```python
odd_numbers = [n for n in range(20) if n % 2 == 1]
```

The same thing exists for dicitonaries for Python versions above 2.7.

A stub for this topic is missing, as far as I can tell.

**Comment by HKuz** [comment]
Hi @pszalanski - I agree that this is an important topic and should be covered! I would request that the article cover the various forms of comprehensions (feedback from other welcome):

- list comprehensions per your example
- dictionary comprehensions as you noted: `{k: v for k, v in iterator}` (where `iterator` returns two items, like `enumerate` or `zip`)
- set comprehension: `{n % 2 for n in range(20)}  # returns {0, 1}` (There are better examples out there, this one is a bit contrived more to show it's similar to lists except it only collects items 1x)
- generator expressions - the article can make the point they're slightly different than list/set/dict comprehensions - they have similar structure, but meant for when you don't need the actual collection, just want to consume it as an iterable (which saves memory): `(n for n in range(20) if n % 2 == 1)`

You're welcome to open a PR to create the stub, and/or take a crack at a 1st draft of the article!

**Comment by pgrzesik** [comment]
hey @pszalanski - are you interested in writing this article ? If not, I'd gladly do it
Regards

**Comment by pszalanski** [comment]
Yes, please go ahead and write it.

**Comment by Tusharchoudhary** [comment]
@pgrzesik hey! have you been working on the article, do you need some help or should I try making the first draft?

**Comment by johnkennedy9147** [comment]
closing as article was created in PR #1770
