### ISSUE TITLE
Yarn Install issue

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/guides#532]
I've been working on my Guides fork for a few days now with no issues. I've even submitted two PR's. However, today I ran `yarn run dev` and I was greeted with some strange dependency error. So I ran `yarn install` and that returned a new uglier error from some `gyp` command. I went ahead and backed up my changed files then I removed my `guides` directory and recloned my fork. After running `yarn install` (on a fresh master fork) I was greeted with this ugly error message:
<img width="1158" alt="screen shot 2017-09-29 at 9 44 20 am" src="https://user-images.githubusercontent.com/16144158/31018787-47f29394-a4fb-11e7-9ff8-230a584a07a9.png">
If anyone has seen this before or know a fix please let me know. I have important changes to push! :laughing:

**Comment by Ethan-Arrowood** [comment]
This was a weird one. Some crazy issue with pre-commit hooks. Just ran rm -f .git/hooks/pre-commit.old and then I was able to use `yarn install` and `yarn run dev` again

**Comment by HKuz** [comment]
Ethen, I had a Python issue when I first ran `yarn install` but got a slightly different error (so take this as more of a datapoint). My install crashed because my bin defaults to Python 3.6 where gyp wanted Python 2.x. When I ran the install in an Anaconda environment for Python 2.7, it worked.

**Comment by Ethan-Arrowood** [comment]
@HKuz I've had similar issues in other projects.

**Comment by HKuz** [comment]
Sorry, Ethan, not Ethen - I turn into fat-fingers McGee on mobile.

**Comment by Bouncey** [comment]
Eevee, nice!

**Comment by Bouncey** [comment]
One of the packages used node-gyp, I though we had got rid of it @systimotic ?

**Comment by systimotic** [comment]
@Bouncey Yep, we did! From the screenshot, I'm seeing that `sharp` is causing the issue, like it was in #348. We removed it through #394.

@Ethan-Arrowood From reviewing your PR, it looks like it may have been a little bit since you last updated your fork. If you didn't do this yet, first add the remote:
```bash
git remote add upstream https://github.com/freeCodeCamp/guides.git
```
Then you can update the current branch with
```bash
git pull --rebase upstream master
```
That should resolve this problem.
