### ISSUE TITLE
Add the page or article name in the commit message

### ISSUE THREAD

**Issue by andres-uris** [freeCodeCamp/guides#5344]
Hello world! 

I think that it would be great if the contributors know if exist some pull request to add or update an article, because we would work in other article or page.

Actually a lot of pull requests just says add someting, update index.md, etc.

Can you update the README and write a recomendation that says "add the article name, that you are working on it,  to the commit message"  ?

This would be very helpful searching on the pull requests and to decide working in different articles.

Sorry for my english, I hope that you can understand me.

**Comment by adiparab14** [comment]
I agree. This is causing multiple updates for the same files. If article name is mentioned in the commit message, a quick search can help.

**Comment by andres-uris** [comment]
@texas2010 Can give us feedback? This can improve the way we contribute to the guide. Check  PR
#5764

**Comment by fvcproductions** [comment]
The idea of having a descriptive title in new PRs has now been integrated with the new pull request template.

I will close this issue for now as the PR referenced above addresses this. https://github.com/freeCodeCamp/guides/pull/6592
