### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tomball** [freeCodeCamp/guides#538]
"Open source" can be a vague term, as it means different things to different people (especially when lawyers are involved). Please add a LICENSE file at the top of your repo that states explicitly what your team wants. It's easiest to choose an existing license and copy its text verbatim, since all the major ones have been carefully reviewed by lawyers throughout the world. 

The [Open Source Initiative](https://opensource.org) has lots of information to help you choose. However, all their site content is covered by the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). Since you're primary focus are your site's articles, perhaps that's the right license to use.

**Comment by texas2010** [comment]
@tomball, thank you for notice that.

@Bouncey @QuincyLarson, it seems we need to add license on this repo.

**Comment by systimotic** [comment]
Great point @tomball, we missed that here! The `package.json` states that we're using MIT, but I think we should probably go with BSD for the code and CC for the content, like with the main repo.

**Comment by shovanch** [comment]
Is anyone working this?

**Comment by texas2010** [comment]
@shovanch you can work on it. 👍

**Comment by systimotic** [comment]
Before you start working on it, we should probably agree on which license to use. I suggested to use BSD for the code and CC for the content, but I think @QuincyLarson should make the final call on this.

**Comment by shovanch** [comment]
Sure. I will wait.

**Comment by QuincyLarson** [comment]
@systimotic Yes - I agree. We want to have two licenses, like we do on the github.com/freecodecamp/freecodecamp repo - BSD-3 for the code and CC-SA-BY 4.0 for the articles themselves.

I've opened a pull request to add these. 

Thanks to @tomball for pointing out that we hadn't yet added licenses.
