### ISSUE TITLE
What about developer.mozilla.org?

### ISSUE THREAD

**Issue by demian85** [freeCodeCamp/guides#539]
I was planning on sending a PR with JS contributions, but then I realized that I would be writing exactly the same as in https://developer.mozilla.org/en-US/docs/Web/JavaScript
Don't you think the purpose of both guides are the same? There should be a way to avoid duplicated documentation!

A good example is the following section: https://guide.freecodecamp.org/javascript/standard-objects
You could easily extract documentation from MDN for those items.

**Comment by johnkennedy9147** [comment]
Hi @demian85 
I disagree, I believe the FCC guide will serve a useful purpose and be complimentary to the existing resources on the internet.

Read @QuincyLarson post on medium to see the intent.
[https://medium.freecodecamp.org/heres-a-new-way-to-learn-coding-tools-and-concepts-right-when-you-need-them-ee82d15c576d](url)

It's still very early days for the project and a lot of the content needs work.

**Comment by systimotic** [comment]
Hi @demian85!

You make a good point, one that I definitely thought about before putting time into this project too. Having a whole section that is merely a copy of what is on MDN seems pointless. I think there is a difference, though.

MDN is amazing reference material that you can definitely use while writing a guide. However, it can be a bit daunting to a beginner. The language used isn't always as simple as it could be. This is the focus of the Guide, guides that beginners can understand too.

We don't mean to make the Guide a replacement of MDN or freeCodeCamp itself. The Guide was made to solve the following problem: a camper needs to reference something. They do a google search. They find something that probably is what they need, but they don't understand what it is or how it works.
The Guide should be the thing they find that they do understand. This is a challenge, and I don't think we're there yet, but that's the direction we want to go in.

From the article linked above:
> This desire for “good enough” explanations inspired us to build the freeCodeCamp Guide.
>
>The Guide is a searchable reference that aims to cover all concepts related to software development.
>
>The articles are simple enough for non-native English speakers to understand them. They’re short enough for busy people to read them while taking a few sips of coffee.

I hope this answers your question. If not, feel free to ask more of them!

**Comment by QuincyLarson** [comment]
I couldn't have said it better than @johnkennedy9147 and @systimotic did. 

I use the MDN as a reference also, along with documentation, Wikipedia, and resources like DevDocs.io. 

With the freeCodeCamp Guide, our goal is instead to offer articles that are "good enough" as opposed to technically exhaustive.
