### ISSUE TITLE
Titles should be formatted correctly

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#54]
Adjust `titleify` found [here](https://github.com/freeCodeCamp/guides/blob/master/_normaliseArticles.js#L61) so that if a stop word (the, of a...) is at the beginning of the string, it must be capitalised.

**Comment by QuincyLarson** [comment]
Also, we need to make exceptions for certain words like SQL and jQuery that have special capitalization. @Bouncey should this be a separate issue or is it related to titleify?

**Comment by Bouncey** [comment]
This is covered in #61 yes
