### ISSUE TITLE
Fix image width in content

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#542]
Currently, there is no maximum width for images. This causes them to overflow:
https://guide.freecodecamp.org/algorithms/binary-search-trees
https://guide.freecodecamp.org/machine-learning/neural-networks
https://guide.freecodecamp.org/meta/free-code-camps-summit-august-2015
and more

The CSS (`src/css/main.scss`) should be updated to give images inside the `.content` a `max-width` of `100%`, and probably `display: block;` too.

**Comment by dhcodes** [comment]
PR submitted. @timo you did all the hard work.
