### ISSUE TITLE
Can't run FreeCodeCamp Guide locally on Bash on Windows

### ISSUE THREAD

**Issue by anku255** [freeCodeCamp/guides#560]
I am using Bash on Windows 10 to run FCC guide locally. When I run the command `yarn run dev` I get ` Error: EMFILE: too many open files, open '{path}/guides/src/pages/mathematics/vectors/curves/index.md'`. 
More about the error can be read in this screenshot below:
![bash_2017-09-30_22-07-57](https://user-images.githubusercontent.com/22813027/31047672-6ecb96e6-a62c-11e7-842f-905bcedbb4e1.png)

`Node version - 8.6.0`
`npm version - 5.3.0`
`Ubuntu version - 16.04`

Can anyone please look into this?

**Comment by Bouncey** [comment]
@anku255 Please try [this answer on SO](https://stackoverflow.com/a/21070580) and let us know how you get on :+1:

**Comment by systimotic** [comment]
@anku255 Hi! Were you able to get it to work using the instructions from the link?

**Comment by systimotic** [comment]
This has been inactive for a while, so I'm closing this. If this is still an issue for anybody, please leave a comment with more information and we'll reopen the issue.

Happy coding!
