### ISSUE TITLE
Add Video Support

### ISSUE THREAD

**Issue by jamesjpk123** [freeCodeCamp/guides#5668]
I wasn't sure if this was already available or not, but I think it wouldn't be s good idea to be able to add videos to our articles. Maybe some people might be able to create videos, for the articles. And if we have that support, maybe we could add support for embedded Scrimba lessons.

**Comment by systimotic** [comment]
Hi @jamesjpk123! You should be able to write HTML in the `index.md` documents, so you can paste a YouTube iframe in there and embed it that way. If this doesn't work, please open a new issue and we'll look into that.

Video's are great, but the Guide is a text-based resource. Not everyone's internet connection can handle a video. When creating a guide, using a video to support your content is a great idea, but always make sure to include all the necessary information in text too.

I'm closing this issue as it should be resolve, we have video support.

Happy coding!
