### ISSUE TITLE
Add BlockChain 

### ISSUE THREAD

**Issue by Mtea994** [freeCodeCamp/guides#5774]
I am creating this issue because i think more people need to know about Blockchain and freecode camp guide is one of the best resources for beginners to learn about new advances in the computer science related field

**Comment by QuincyLarson** [comment]
@Mtea994 agreed - would you be interested in helping us write some articles about various aspects of blockchain?

**Comment by Mtea994** [comment]
Sure why not.currently i working on a project based on blockchain i will share some details but i am not very qualified i am still an undergrad student so you and others much qualified than me should review it

**Comment by QuincyLarson** [comment]
@Mtea994 Awesome - I've merged your PR to create the stub. Thanks in advance for your help adding new topics and - as time permits - articles :)
