### ISSUE TITLE
search does not seem to be working...

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/guides#5791]
not sure if this is best opened here or in the search engine repo, but the guides search does not seem to be working at the moment. Can anyone else confirm this?

![image](http://g.recordit.co/ouTtmeRuF1.gif)

**Comment by systimotic** [comment]
@no-stack-dub-sack It appears to be working fine for me. Can you look at the network tab in the devtools and see if that gives any information about what is going on?

**Comment by IsaacAbrahamson** [comment]
I can confirm I had this issue a few days ago, but looking at it today it seems to be working.

**Comment by no-stack-dub-sack** [comment]
@systimotic @IsaacAbrahamson I just remembered this and checked again and it is working now. So not quite sure what was going on. We can probably safely close this for now until it can be reproduced and we can identify a cause.

**Comment by IsaacAbrahamson** [comment]
@no-stack-dub-sack, yeah I can no longer reproduce either. I'm going to close following your suggestion.
