### ISSUE TITLE
Font-Awesome Article?

### ISSUE THREAD

**Issue by BitYog** [freeCodeCamp/guides#612]
It is in the freeCodeCamp curriculum and is usually helpful for beginners. Can add an article on it in the Bootstrap section. Proceed?

**Comment by systimotic** [comment]
@BitYog Sounds like a good idea to me! I'm not sure if the Bootstrap section is a good place for it, though. The two aren't really related. Maybe it should be in `Miscellaneous`?

**Comment by johnkennedy9147** [comment]
@BitYog @systimotic Font-Awesome is a CSS framework so may fit best in there? Or maybe a new top-level dir for these awkward to categorise web development tools (Bootstrap would fit in there with FA rather than be its own category)

**Comment by systimotic** [comment]
@johnkennedy9147 I'm not sure if FontAwesome counts as a CSS framework, I think of it as a library. I think Bootstrap is absolutely a CSS Framework. Its directory might have to be moved to the `CSS Frameworks` directory.

**Comment by johnkennedy9147** [comment]
@systimotic actually I totally agree now that I think about it, despite calling themselves "the iconic font and CSS framework" Font Awesome doesn't actually satisfy the requirements to be considered a framework.  But I would say neither does Bootstrap, they are both libraries arent they? Bootstrap also is not just CSS so would it be appropriate to categorise under CSS?

**Comment by BitYog** [comment]
As @johnkennedy9147 has already created a Frameworks and Libraries section, we can add the Font-Awesome article in it. @systimotic @johnkennedy9147 can we start creating the article now?

**Comment by systimotic** [comment]
@BitYog You can definitely start creating the article, we can always move it later. Where is the frameworks and libraries section? I'm not seeing anything apart from an open PR specifically for JS frameworks and libraries.

**Comment by johnkennedy9147** [comment]
@BitYog 
The section you saw referenced in the issue #494 is just for Javascript frameworks and articles, so Font Awesome wouldn't belong in there. 
@systimotic I'm still liking a new Web Development Toolkits section for awkward things that are important but dont fit neatly somewhere else. What do you think?

**Comment by systimotic** [comment]
@johnkennedy9147 I'm not sure. I'd like to avoid sections that have a few articles. Maybe the best way to go about this is adding it to misc until we have enough content to create a new section for this.
