### ISSUE TITLE
Miscellaneous cleanup

### ISSUE THREAD

**Issue by BitYog** [freeCodeCamp/guides#615]
1) JavaScript articles included in miscellaneous. Eg, <a href="https://guide.freecodecamp.org/miscellaneous/stringprototypelastindexof"> String.prototype.lastIndexOf() </a> or <a href="https://guide.freecodecamp.org/miscellaneous/equality-vs-identity-operator"> Equality & identity operator. </a> 
2) Python articles. Eg, <a href="https://guide.freecodecamp.org/miscellaneous/python-function-divmod"> Divmod function </a> 
3) Git articles... Many of them.

There are many more examples, and I could go on and on. This is an enormous task, and needs several permissions by the authors after PRs are opened. Also, how do I move the articles and delete some of them? Help??

**Comment by systimotic** [comment]
Hi @BitYog! Most of the articles in the Guide were imported from the forum. We categorized the ones we easily could. Everything else was put in `Miscellaneous`. As you correctly noticed, everything in there still needs to be put in the correct place. Any help with this would be greatly appreciated.

When manipulating the file structure a lot, the easiest solution might be to clone your fork and do it locally. You could do this using the git cli, or you can use [GitHub Desktop](https://desktop.github.com/).

It's also possible to do this in the GitHub web interface: https://help.github.com/articles/moving-a-file-to-a-new-location/ However, this can be a bit of a hassle when you need to move a lot of files.

**Comment by invinciblycool** [comment]
@BitYog I could help in moving the Python articles :smile:

**Comment by systimotic** [comment]
@invinciblycool That would be great! Be sure to check for duplicates while you're moving articles 👍

**Comment by dhanushuUzumaki** [comment]
@BitYog Can I help in moving the git articles?

**Comment by BitYog** [comment]
@dhanushuUzumaki Yeah, you can.

**Comment by BitYog** [comment]
@systimotic I am doing these changes on a Windows machine with Github Desktop. I have done some of the work required. How do I open a pull request when I'm completed??

**Comment by dhanushuUzumaki** [comment]
@BitYog  I believe you have forked this repo and made your changes. Just commit and push to your forked version. When you visit your forked repo page on GitHub, there will be an option to create a PR. If you prefer using CLI, then you could try [this](https://git-scm.com/docs/git-request-pull).

**Comment by BitYog** [comment]
@systimotic @invinciblycool @dhanushuUzumaki I've done the changes in GitHub Desktop, but I'm not able to make a pull request on the website.

**Comment by dhanushuUzumaki** [comment]
@systimotic just making sure, after making the changes did you commit and push those changes to your repo?

**Comment by BitYog** [comment]
Yeah, I did. But it still doesn't show up on GitHub.

**Comment by systimotic** [comment]
@BitYog There should be a "Publish this branch to GitHub" button. Click that. After that's done, go to the main page of this repo: https://github.com/freeCodeCamp/guides
It should say that you recently pushed new changes, and show a button to create a Pull Request.

**Comment by BitYog** [comment]
@systimotic @invinciblycool @dhanushuUzumaki  I've created PR #698. Reviews will be very helpful.

**Comment by BitYog** [comment]
@systimotic @invinciblycool @dhanushuUzumaki Created a new PR - #733 to fix this issue. Need reviews, so that there are no random additions or deletion. Let's finally make some progress here.

**Comment by BitYog** [comment]
@systimotic #733 The changes you requested are done. I have added the relevant commit.

**Comment by l34kr** [comment]
Would like to help on this too if there's any more help needed :) But better wait for the changes of @BitYog getting merged =D

**Comment by BitYog** [comment]
@invinciblycool @dhanushuUzumaki I’m closing this issue. If you still want to contribute, you can copy my changes and open a new PR. Just credit me somewhere in the comments.
@l34kr Thanks, but my changes aren’t getting merged. Can you help with #612?

**Comment by artismarti** [comment]
@BitYog I was thinking of writing a quick guide on FontAwesome - based on #612.
Where shall I write this?

**Comment by BitYog** [comment]
@artismarti I think the designer tools section would be the best place.
