### ISSUE TITLE
Remove duplicate articles in javascript

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#62]
Whilst working on a different PR, I noticed at least three different articles talking about `Array.prototype.forEach`

**Comment by invinciblycool** [comment]
As a beginner I would like to take this up but after going through all array methods I find that all of the methods have at least three different articles.
Should all of them be corrected?

**Comment by Bouncey** [comment]
@invinciblycool #74 addresses this. Thanks for your interest in contributing towards this
