### ISSUE TITLE
Images for Block and Inline Element

### ISSUE THREAD

**Issue by srawat19** [freeCodeCamp/guides#623]
![inline_output](https://user-images.githubusercontent.com/16048167/31069389-e1e3fc10-a779-11e7-86d2-6685e0061f52.png)

**Comment by srawat19** [comment]
![block_output](https://user-images.githubusercontent.com/16048167/31070017-6f2cf0a2-a77c-11e7-9de6-110b9d0b488d.PNG)

**Comment by srawat19** [comment]
Added Block level example snapshot

**Comment by systimotic** [comment]
Hi @srawat19, thanks for contributing! Please refer to https://github.com/freeCodeCamp/guides#adding-images-to-articles for adding images to your guide.
