### ISSUE TITLE
Images broken in webpage

### ISSUE THREAD

**Issue by pranabendra** [freeCodeCamp/guides#663]
When I view the article <a href="https://github.com/freeCodeCamp/guides/blob/5ebf839b98db808c35f2a47e176b195fdc36edd3/src/pages/mathematics/differential-equations/eulers-method/index.md">herein</a>  Github, all the images appear properly.

![image](https://user-images.githubusercontent.com/30474395/31128919-be2f1d84-a870-11e7-8ab2-cc2b75461f75.png)

But, upon viewing the article <a href  = "https://guide.freecodecamp.org/mathematics/differential-equations/eulers-method">here</a>, the images seem to be broken.

![image](https://user-images.githubusercontent.com/30474395/31129506-61770f6e-a872-11e7-8349-f04183830273.png)

Can anyone please enlighten me on this? Thanks in advance.

**Comment by texas2010** [comment]
oh, I see. you added a link at that. I look it up. it is a page. it supposes to be picture file. not website page.

for example, you use this link. https://github.com/pranabendra/articles/blob/master/Euler-method/images/eqn1.png   you could notice it is a website page. not picture file.

**Comment by dhanushuUzumaki** [comment]
It is just as @texas2010  pointed out. If a link to the correct image is used then it is properly displayed. 
<img width="1280" alt="screen shot 2017-10-03 at 8 03 23 pm" src="https://user-images.githubusercontent.com/14927280/31130839-2300afa2-a876-11e7-8a09-ed61406e6f22.png">

**Comment by pranabendra** [comment]
Thanks a lot! @texas2010 @dhanushuUzumaki 

Understood my mistake. I'm fixing all of them.

**Comment by systimotic** [comment]
Thanks for catching the error and figuring out what to do @pranabendra @texas2010 @dhanushuUzumaki! I'm closing this issue as resolved.

Happy coding!
