### ISSUE TITLE
Make all typeface on guide articles Lato

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#67]
We should replace the current font on the guide articles with Lato so it's consistent with the rest of the text on freeCodeCamp. We should also bump the font size up to at least 14px.

**Comment by vikramnr** [comment]
@QuincyLarson  Is it with README.md file??

**Comment by Bouncey** [comment]
@vikramnr thank you for the interest in helping us fix this. The code for font styles is in `src/utils/typography.js`, [here is the reference](https://www.npmjs.com/package/typography) for adjusting the font styles. 

Happy coding!

**Comment by vikramnr** [comment]
@Bouncey  I'll give it a try
