### ISSUE TITLE
Test markdown articles for frontmatter with Travis-CI

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guides#675]
All markdown articles need 
```yml
---
title: A Nice UI Title
---
```
At the top of the file

We could just ask Travis to `node bin/createNavData` As part of the CI tests

This will give a clear indication to maintainers that the articles won't break the build

**Comment by texas2010** [comment]
Yes! good idea.

**Comment by johnkennedy9147** [comment]
@Bouncey I've never used (or even seen) travis or node before but I think what you mean is that the command needs to be added to the file travis.yml in the script section? that will make travis run that node file during each build, and node will return an error code if the title section is missing therefore avoiding the issue of breaking the build if a file is committed sans title.

**Comment by dhanushuUzumaki** [comment]
I believe, please correct me if wrong, that createNavData is currently not throwing an error if the title data is not present; Should that be added? [getTitle is called here](https://github.com/freeCodeCamp/guides/blob/011475f6f6bb6b9413d9af230992d2a1ff76209f/bin/createNavData.js#L23)

**Comment by Bouncey** [comment]
[this line](https://github.com/freeCodeCamp/guides/blob/011475f6f6bb6b9413d9af230992d2a1ff76209f/bin/createNavData.js#L12) throws an error when the frontmatter is missing. 

If this line fails, it would be a good idea to throw an error with the message adout missing frontmatter. Thanks for the suggestion @dhanushuUzumaki 

@johnkennedy9147 you are correct, `node bin/createNavData` should be added to the scripts section of the `.travis.yml`

**Comment by johnkennedy9147** [comment]
@Bouncey submitted PR #691  to add requested command

**Comment by johnkennedy9147** [comment]
@Bouncey Question: I took a look at Travis as it was doing its checks on my PR and the line I added was ran, even though the PR isn't committed yet. Should that happen?

![image](https://user-images.githubusercontent.com/26827682/31165246-3f00a7a4-a8e2-11e7-8e7f-188f10faa6cb.png)

It seems wrong, and potentially dangerous to me, for changes to immediately take effect. Though with my very limited knowledge of Travis maybe I am overestimating the potential harm buggy or malicious code in the file could cause.

**Comment by Bouncey** [comment]
Travis takes it's setting from the .travis.yml file that is on the PR. So this is normal. It does not effect any other PRs until it is merged

**Comment by Bouncey** [comment]
@johnkennedy9147 would you be comfortable with making [this line](https://github.com/freeCodeCamp/guides/blob/011475f6f6bb6b9413d9af230992d2a1ff76209f/bin/createNavData.js#L12) throw an error if it fails?

**Comment by johnkennedy9147** [comment]
@Bouncey I took a look at the code and this is what I came up with:

`function getPageTitle(content) {
 let meta;
 try {	
 // meta = '---\ntitle: Frontmatter Title\n---'
 meta = content.match(metaRE)[0];
 }
 catch (err){
 if (err instanceof TypeError){
	 err.message ="Frontmatter may be missing from an article."; 
 }
 console.error(err);
 throw  err;
 }
  return meta.split('\n')[1].replace('title: ', '');
}`

**Comment by systimotic** [comment]
@johnkennedy9147 Nice work! I think it could be simplified a little bit:
```js
function getPageTitle(content) {
  try {	
    // meta = '---\ntitle: Frontmatter Title\n---'
    const meta = content.match(metaRE)[0];
    return meta.split('\n')[1].replace('title: ', '');
  } catch (err) {
    throw 'Frontmatter may be missing from an article.';
  }
}
```
Of course, I had to test before sharing, but I got a little carried away: https://github.com/systimotic/guides/commit/283a1b7fd4eb604060181175e5afd0f8a8768e66 😄

**Comment by Bouncey** [comment]
@johnkennedy9147 could you implement @systimotic's `getPageTitle()` please 👍

**Comment by johnkennedy9147** [comment]
@systimotic 2 questions:
Would mine have worked?
Does the example you posted above throw 2 errors, firstly a typeerror then maybe a referenceerror, or would it have kicked out of try block at typeerror? I think the latter.

**Comment by Bouncey** [comment]
@systimotic if you could commit `23a1b7` to @johnkennedy9147 PR I would gladly merge 👍

**Comment by Bouncey** [comment]
It will `try` to run the code block without expections. If an exection occurs, the `catch` code block runs

**Comment by systimotic** [comment]
@johnkennedy9147 Absolutely, yours worked perfectly!
My version throws only a single error, yours actually showed the error twice 😄 `console.error` showed it the first time, then again on `throw`. I know that we did that later in the same file too, but it's redundant.
As Stuart explained, when there is an error in the `try` block, it will skip to the `catch` block. Using this, I could for example return a default title in the catch for any article with an invalid one:
```js
function getPageTitle(content) {
  try {	
    // meta = '---\ntitle: Frontmatter Title\n---'
    const meta = content.match(metaRE)[0];
    return meta.split('\n')[1].replace('title: ', '');
    // returns "Frontmatter Title" for meta from previous comment
  } catch (err) {
    // If there were no errors, this never executes
    // If there was an error, I won't throw it now
    // I'm returning a default instead
    return 'Unnamed article';
    // Things will keep on going, no errors are ever shown.
  }
}
```

**Comment by johnkennedy9147** [comment]
thanks @Bouncey @systimotic
