### ISSUE TITLE
Search bar typeahead

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#69]
The search bar should support typeahead, so that when you start typing "sq" a dropdown shows you relevant search results with each new keystroke, like "sql" and "sql insert", which you can click on to navigate directly to the article.

This should also support basic keyboard interaction: the up and down arrow keys to select a result, the enter key to open selected result, and escape to dismiss suggested results.

We should show the titles of up to 8 matching results (they needn't be capitalized).

Here's what Facebook's look like: 

![_132__facebook](https://user-images.githubusercontent.com/985197/28255167-599688d8-6a79-11e7-906e-aabba0ee2ebf.png)

Nothing fancy - just fast and functional :)

**Comment by Bouncey** [comment]
https://github.com/Bouncey/react-freecodecamp-search/issues/30
