### ISSUE TITLE
add command line/terminal guide

### ISSUE THREAD

**Issue by philliplaibe** [freeCodeCamp/guides#7483]
Add folder to have guides about using command line including frequently used commands such as cd for change directory, l for list etc.

**Comment by jp-sauve** [comment]
I've written about this, hopefully at enough length. Check out the PR and comment!
https://github.com/freeCodeCamp/guides/pull/7564

**Comment by fvcproductions** [comment]
Closing as above PR mentioned addresses this. :smile:
