### ISSUE TITLE
Vim: Duplicate content

### ISSUE THREAD

**Issue by jp-sauve** [freeCodeCamp/guides#7787]
There is significant duplicate content on the following pages of the Vim section:
https://guide.freecodecamp.org/vim/modes
https://guide.freecodecamp.org/vim/useful-commands

**Comment by thepriefy** [comment]
I wanna do this one. What is the expected output?

**Comment by chotuaashiq** [comment]
@jp-sauve I think that the https://guide.freecodecamp.org/vim/modes page can be merged with the https://guide.freecodecamp.org/vim/useful-commands page and then make it a single page, which will be containing both the modes as well as the commands. It will reduce (almost nullify) the duplicated content as well as the number of pages to be maintained will also be reduced.

**Comment by thepriefy** [comment]
@chotuaashiq @jp-sauve Should I move the content from 'useful-command' page and move it to 'modes' page so I don't need to create a new page?

**Comment by Pherang** [comment]
It doesn't look like there's been any updates to this one. I can try if no one's actively working on this.

**Comment by Asjas** [comment]
@Pherang Sure you can take this :+1:

**Comment by Pherang** [comment]
@Asjas Thanks, will see what I can do.

**Comment by Pherang** [comment]
Hi everyone,

I've put in a PR for this. Let me know if it helps and if not, what might work better.
Thanks.

**Comment by ayushpratap** [comment]
If there is any progress on this then it's okay or else I'd like to take it up.

**Comment by ayushpratap** [comment]
I understand that , I am saying if this PR is not accepted and and the PR owner do not work on it further , in that case I will be happy to take it up.
