### ISSUE TITLE
Fix Readme links

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#7798]
I found a few non-functional links in the newly-update Readme:

![freecodecamp_guides__a_collection_of_easy-to-understand_guides_to_programming_tools](https://user-images.githubusercontent.com/985197/32360946-c3b8db12-c028-11e7-98eb-4d695e9732dd.png)

These seem to have been introduced by @fvcproductions's Readme update: https://github.com/freeCodeCamp/guides/pull/7784

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by adiparab14** [comment]
@QuincyLarson please review

**Comment by Bouncey** [comment]
fixed via #7800
