### ISSUE TITLE
MathematicsDerivatives: Images not rendering

### ISSUE THREAD

**Issue by luandy64** [freeCodeCamp/guides#7841]
While I was scrolling through topics to see people's writing styles, I noticed these images not appearing.

<img width="1280" alt="fcc_error" src="https://user-images.githubusercontent.com/19473996/32645916-4f405b84-c5af-11e7-9da2-6663bc0ec6ec.png">

---

> ✅️ By submitting this issue, I have verified the following

- [X] [hecked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [X] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
@luandy64. Hi, I just checked the [freecodecamp docs](https://guide.freecodecamp.org/mathematics/derivatives) and you are correct that the images are not displaying. I suspect it's because the docs haven't been updated yet. 

If you browse on github to the latest [master copy](https://github.com/freeCodeCamp/guides/blob/master/src/pages/mathematics/derivatives/index.md) you will see the images are working. Once the freecodecamp guide is updated the images will work

**Comment by Asjas** [comment]
Please let me know if this issue can be closed 👍

**Comment by johnkennedy9147** [comment]
@luandy64 @Asjas looks like the link in the img tag is to the page on github for the image, rather than the raw image compare results of these two links:
https://github.com/MarkMikow/MyFiles/blob/master/img3.png
https://github.com/MarkMikow/MyFiles/blob/master/img1.png?raw=true

**Comment by luandy64** [comment]
@Asjas @johnkennedy9147 If either of you would like to handle this, that'd be great. I was just pointing out my finding.

**Comment by johnkennedy9147** [comment]
Anybody who wants to fix this feel free.
You can ask me if you need guidance.
thanks

**Comment by adiparab14** [comment]
@johnkennedy9147 Please check

**Comment by johnkennedy9147** [comment]
@adiparab14 Hi, thanks for the PR. I have merged it. However, I noticed afterwards there 3 more images that aren't loading in the article. Would you like to fix those too?

**Comment by adiparab14** [comment]
@johnkennedy9147 Done

**Comment by systimotic** [comment]
I'm closing this, as it has been fixed through #7845. Thanks for reporting this, looking into it and fixing it everyone! Happy coding 😃
