### ISSUE TITLE
Duplicate Stubs: Pythagoras Theorem and Pythagorean Theorem

### ISSUE THREAD

**Issue by luandy64** [freeCodeCamp/guides#7842]
Pythagorean Theorem should probably be the one that is kept

---

> ✅️ By submitting this issue, I have verified the following

- [X] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [X] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
merged #7880 issue resolved
