### ISSUE TITLE
CSS preprocessor section returns "404 Page Not Found" error

### ISSUE THREAD

**Issue by vijayabharathib** [freeCodeCamp/guides#7867]
Hi there, 

I was trying to access **CSS > CSS Preprocessors** section. The link returned **404 - Page Not Found** error. Screenshot attached.
![github-issue-css-preprocessors-404-not-found](https://user-images.githubusercontent.com/15519267/33034000-79a7085a-ce4c-11e7-9007-aa03f537a197.png)

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @vijayabharathib.

Thanks for picking that up. I just noticed that the `title` of the page isn't correct. That is why it's not loading the website correctly.

Anyone is free to open a PR and fix this.

**Comment by Asjas** [comment]
@vijayabharathib Thanks for your PR. The CSS Preprocessors page is now loading and the `Title` is displaying as it should. :tada:

**Comment by vijayabharathib** [comment]
@Asjas, handing it over to @RohanGurjar who seems to have created the PR. 👏 👏
