### ISSUE TITLE
Collapse nav on mobile

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#7877]
At the moment using the guide on a mobile device is difficult due to the navigation being long, it takes lots of scrolling and avoiding tapping a new article to get to content. There should be a way to collapse the navbar after selecting a guide article.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by systimotic** [comment]
Absolutely agree! We already have an open issue and PR about this: https://github.com/freeCodeCamp/guides/issues/298
I'm closing this as a duplicate.

Happy coding/reviewing!
