### ISSUE TITLE
Front-matter detection breaks on edge case

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#7884]
## Problem

There's an edge case that our front-matter regex doesn't catch. This came to light through https://github.com/freeCodeCamp/guides/pull/7855
The regex:  https://github.com/freeCodeCamp/guides/blob/4c39e4939e3290afbda8c8dd91fa1329e9ea6920/utils/regEx.js#L5
What it should match:
```
---
title: CSS-Preprocessors
---
```
The edge case (it shouldn't match this):
```
----
title: CSS-Preprocessors
----
```
You can see it in action here: http://regexr.com/3h8ht

## Possible solutions
These solutions would both work fine.

### 1. Update the regex
This issue can be fixed by updating the regex to look for the beginning and end of lines.
```js
/^---\s*title:([^\n]*)\n---$/m
```
https://regexr.com/3h8hq

### 2. Use a tool to detect front-matter
We use Gatsby to transform our Markdown files and templates into a static site. Through `gatsby-transformer-remark`, it uses the [`gray-matter`](https://www.npmjs.com/package/gray-matter) package to parse front-matter. We could use `gray-matter` instead of a regex. This would add another dependency, but it would probably be the most robust solution. If you decide to go this route, keep an eye on the time it takes to generate the navData. I'm interested to see whether this has a significant (positive or negative) impact on performance.

---

It would be nice to get this fixed, but it's not extremely urgent as it really is an edge case. This issue is open to anyone, but if you've never contributed to the platform before, it's a good place to get started.

**Comment by chotuaashiq** [comment]
@systimotic I am interested in solving the issue. I am comfortable with the regex thing, but I am not getting the detection of front-matter thing. Can you help me in that?

**Comment by systimotic** [comment]
Thanks for the PR @chotuaashiq! We don't need to implement both solutions, using only a regex would be fine too. On a second thought, sticking with the regex might be better, as we're using it for the breadcrumbs too.

If you do want implement gray-matter instead of using a regex, you'll have to change this function:
https://github.com/freeCodeCamp/guides/blob/069f005094b71df4c9b67980e6099b4178ce7239/bin/createNavData.js#L10-L16
That should be moved to the utils and imported into this file and the breadcrumbs file. Instead of using the regex, it should pass `content` to the `gray-matter` function (check the usage instructions on the linked shared previously). It will return an object that contains our `title`. If it exists, you'd return it from the function. If the title does not exist on the object, or if it's empty, it should throw the error.
