### ISSUE TITLE
Title meta property for an article should include topics it's nested topics as well

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#7897]
Currently the Title property just states the title of the article, which in some cases isn't all that helpful:

![sharing_debugger_-_facebook_for_developers](https://user-images.githubusercontent.com/985197/33284924-4ac1c578-d376-11e7-9f01-9e5f86a7e34d.png)

Instead, we should also pull in the topics that article is nested within. For example:

C > Appendix

or: 

Mathematics > Algebra > Piecewise Functions Graphs

**Comment by spezzino** [comment]
This was fixed on #5225

**Comment by systimotic** [comment]
Looks like this is working to me too 🎉 Thanks @spezzino

**Comment by QuincyLarson** [comment]
@spezzino Awesome! Thanks for fixing this.
