### ISSUE TITLE
Incorrect url in Contributing.md

### ISSUE THREAD

**Issue by adiparab14** [freeCodeCamp/guides#7913]
In Contributing.md, in the Table of Contents, the url for Closing Templates for Reviewing PR's is incorrect
---

> ✅️ By submitting this issue, I have verified the following

- [X] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by adiparab14** [comment]
Current it is pointing to the Closing under the Getting PR accepted topic

**Comment by ArmenGabrielyan16** [comment]
@adiparab14 Thank you. I addressed this issue in PR #7914.
