### ISSUE TITLE
A little Mistake :3 

### ISSUE THREAD

**Issue by zoubiforat** [freeCodeCamp/guides#7915]
Under "Object Oriented and Function Programming" -> "Make Instances of Objects with a Constructor Function":
this is written in the yellow box
```js
{
  wheels: 4,
  engines: 1,
  seats: 5
}
```
but i think how i understood, it should be :
```js
{
  "wheels": 4,
  "engines": 1,
  "seats": 5
}
```

_Formatting edited by Timo_

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by systimotic** [comment]
Hi @zoubiforat!

I believe you're talking about https://www.freecodecamp.org/challenges/make-instances-of-objects-with-a-constructor-function, which is a part of the core freeCodeCamp curriculum, not the Guide.

For help with the challenges, please use the forum: https://forum.freecodecamp.org/

Happy coding!
