### ISSUE TITLE
Code Coverage in wrong location

### ISSUE THREAD

**Issue by jp-sauve** [freeCodeCamp/guides#7950]
It seems to me that an article about code coverage should be in the software engineering section. Right now it's https://guide.freecodecamp.org/developer-tools/code_coverage but it's not a "tool" in the manner of the other pages in this category. I have merged #2983 but now one of the pages needs to be moved or deleted.

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by chotuaashiq** [comment]
@jp-sauve Yes the code coverage article in the tools should be deleted . Should I open a PR?

**Comment by jp-sauve** [comment]
Sure, that would be great! That is assuming there isn't one in the works right now.  :)

**Comment by systimotic** [comment]
I'm closing this as this has been resolved, thanks @chotuaashiq and @jp-sauve!
