### ISSUE TITLE
Absolute / Relative URL mistake in search results

### ISSUE THREAD

**Issue by lsenta** [freeCodeCamp/guides#7953]
Hi there, thanks for providing this guide.
The links in the search results are malformed:

1. visit https://guide.freecodecamp.org/search
2. type something (`database`)
3. The result links to: `https://guide.freecodecamp.org/https://guide.freecodecamp.org/computer-science/databases/graph-databases`

I guess the code switching from relative to absolute URLs was mishandled.

**Comment by antigone2** [comment]
Cmon guys, you have hrefs like "href="/https://guide.freecodecamp.org/miscellaneous/getting-started-with-sass".

Second problem: if you are the bottom-est level, meaning reading targeted article, the search won't work.
