### ISSUE TITLE
Cannot install guides nor run guides using yarn

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guides#796]
When attempting to install and run the guides project with yarn using the instructions provided at https://github.com/freeCodeCamp/guides#running-the-guide-locally-on-your-own-computer I get an error. The error output is as followed.

**"yarn install" output:**
```
Nathaniels-MacBook-Pro:guides nathanielsuchy$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠂ fsevents
[2/5] ⠂ uws
[3/5] ⠂ node-sass
[4/5] ⠂ spawn-sync
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
error An unexpected error occurred: "/Users/nathanielsuchy/Documents/Coding/guides/node_modules/spawn-sync: Cannot read property 'config' of undefined".
info If you think this is a bug, please open a bug report with the information provided in "/Users/nathanielsuchy/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**"yarn run dev" output:**
```
Nathaniels-MacBook-Pro:guides nathanielsuchy$ yarn run dev
yarn run v0.27.5
$ node bin/createNavData && gatsby develop
Creating navData...
navData created
It took 4850ms to create the navData for 2455 pages
success open and validate gatsby-config.js — 0.012 s
success copy gatsby files — 0.074 s
success source and transform nodes — 40.468 s
success building schema — 2.486 s
success createPages — 18.656 s
success createPagesStatefully — 1.357 s
success extract queries from components — 0.354 s
success run graphql queries — 48.132 s
success write out page data — 0.114 s
success update schema — 22.639 s

bootstrap finished, time since started: 141.89 s



 ERROR  Failed to compile with 1 errors                                                                                                                                  11:49:33 AM

 error  

ENOENT: no such file or directory, scandir '/Users/nathanielsuchy/Documents/Coding/guides/node_modules/node-sass/vendor'

 @ ./src/css/main.scss 4:14-150 13:2-17:4 14:20-156
```

**Comment by systimotic** [comment]
We discussed this on Gitter. We found that running the following commands solved problem:
```
yarn global add node-gyp
rm -rf  node_modules
yarn install
```
The main error is this line:
> error An unexpected error occurred: "/Users/nathanielsuchy/Documents/Coding/guides/node_modules/spawn-sync: Cannot read property 'config' of undefined".

I couldn't find a lot of information about this. The only related thing I could find was this issue: https://github.com/yarnpkg/yarn/issues/3825. It suggests it was a cache issue, which would be possible given the things we saw (removing existing modules was required to make it work). The manual `yarn global add node-gyp` was likely not required, but it's difficult to test that now.
@nsuchy If you're willing to try to test this, run the following commands and check if you can still run the Guide:
```
yarn global remove node-gyp
rm -rf  node_modules
yarn install
```

I haven't heard of anybody having this error before. If this was only a very rare thing, this may be resolved now. If it is more common, we might need to document it. If the test above gives the same error again, this is probably a more common issue. If it the test runs successfully, it's unlikely somebody else will also run into this.

@nsuchy If `/Users/nathanielsuchy/.config/yarn/global/yarn-error.log` still exists, can you share it in a Gist or a Pastebin? Although I don't expect it to have any valuable information in this case, it can't hurt to double-check.

**Comment by systimotic** [comment]
Closing as stale. If anybody runs into this problem in the future, please comment here and we'll look into it further. Happy coding!
