### ISSUE TITLE
Remove unnecessary files, e.g. examples

### ISSUE THREAD

**Issue by kuriakinzeng** [freeCodeCamp/guides#8]

**Comment by Bouncey** [comment]
Why are we nesting projects?

**Comment by kuriakinzeng** [comment]
We used a starter template provided by Gatsby. I'm still getting into why they are doing this. It sounds to me that we are not going to do a lot of modifications apart from stylistic.

**Comment by Bouncey** [comment]
The `gatsby new gatsby-documentation-site https://github.com/gatsbyjs/gatsby-starter-documentation` is broken with `gatsby@1.0.0-alpha21` I suggest we work with the latest release until the release of `v1`. There is a migration guide [here](https://deploy-preview-1044--gatsbyjs.netlify.com/docs/migrating-from-v0-to-v1/)

The project at the minute is chaotic

**Comment by kuriakinzeng** [comment]
When you say latest release you are referring to the latest stable release right?
  
  

  
>

**Comment by Bouncey** [comment]
Yes, the last stable release

**Comment by Bouncey** [comment]
#12 closes this
