### ISSUE TITLE
Plans for a CMS?

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guides#8006]
Hi, I'd like to know if there is a plan to use some sort of CMS for the freeCodeCamp Guide. I saw a solution based on Netlify CMS being evoked [here](https://github.com/freeCodeCamp/guides/pull/22#issuecomment-308833675) and [there](https://github.com/freeCodeCamp/guides/issues/16#issuecomment-308679342), is it still being envisioned or discussed?

I'd be interested to know about such a solution if you guys were planning on implementing one for the Guide, or even if you just know that it exists.

I am myself building a wiki website and [I'm looking for a headless CMS designed designed for powering a wiki](https://stackoverflow.com/questions/48233396/headless-cms-for-powering-a-wiki-allow-editing-by-anyone-like-on-wikipedia) (a headless wiki engine, if you prefer). My goal is to have the site statically generated with Gatsby while providing a user-friendly interface for non-technical users to edit content (something easier to use than GitHub for non-developers).

I thought the freecCodeCamp Guide might have similar needs, and I saw the topic being evoked, so I figured I'd ask if you guys had plans to implement something of this sort, or if you know about a solution to this use case.

Thanks a lot!

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
@QuincyLarson to comment

**Comment by QuincyLarson** [comment]
@thomaskuntzz @johnkennedy9147 We are planning to add Netlify CMS to the Guide in the near future. @Bouncey is going to work on integrating this as soon as we ship beta. If you want to see this in action, here's a nice blog post with a video that shows the CMS in action: https://kalinchernev.github.io/admin-ui-gatsby-static-site-generator/

**Comment by thomaskuntzz** [comment]
Cool, I'm curious to see how it will look once shipped!

**Comment by thomaskuntzz** [comment]
Especially, how are you going to handle authentication? To my knowledge, Netlify CMS requires to create an account in order to edit content. Do you have a workaround for this, or do you consider that it will still be easier than GitHub for a non-developer audience?

I think that's the main problem for the wiki use case: the software has to be designed to allow editing from anyone, and to work well with this. That's why I asked how you were planning to handle this, as I don't know any Headless CMS designed for powering wikis...

**Comment by QuincyLarson** [comment]
@thomaskuntzz I'm not sure whether it will be possible to get around creating a Netlify account. Considering you can auth into Netlify GitHub, even if that's required it shouldn't be a huge hurdle to contributing. @Bouncey will investigate this when we get to that step :)

**Comment by Bouncey** [comment]
At the minute netlify support google and github OAuth, as well as email verification. They also offer some form of role management (writers, editors, publishers ...).

It will hopefully make it easier to contribute to the guide for people to cannot/do not want to use git.

**Comment by QuincyLarson** [comment]
@Bouncey OK - great. Thanks for the additional explanation.

@thomaskuntzz people who want to use Git will still be able to submit changes through pull requests manually, too.

**Comment by thomaskuntzz** [comment]
Cool, thanks for the answers!

Should we close this? It mas more of a question than an actual issue...

**Comment by johnkennedy9147** [comment]
Had a play with Netlify CMS today. I think it will work well for making it easier for people to contribute to Guides.
@thomaskuntzz should be good for your wiki too - very low barriers to entry for non-technical people

**Comment by thomaskuntzz** [comment]
Sure, much lower barriers to entry than GitHub, especially with Google OAuth, but I would love to see a headless wiki engine that doesn't even require to create an account at all, exactly the same way that Wikipedia allows anyone to edit content anonymously. Even lower barriers to entry: you just click edit and make your change, no account required. But to my knowledge, this doesn't exist right now, that's why I asked 😉

**Comment by QuincyLarson** [comment]
@johnkennedy9147 Awesome! I'm glad to hear you got a chance to play with it, and you think it's a good fit :)

@thomaskuntzz Wikipedia is a bit different in that there might be reasons why you'd want to be able to anonymously edit an article (especially in some countries, for some topics). For the guide, I doubt there will be anything too controversial in there. Since these are coming through PRs we need to know where the PR is coming from so we can follow up for clarification if necessary. So there are a lot of advantages to knowing who is making the edit.
