### ISSUE TITLE
Why external hosting for images?

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guides#8010]
I saw [here](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#images) that we have to upload images to an external image hosting service. Why is that? Why can't we just put them in the git repo alongside with the articles? Would it make the repo to big or is it for some other reason?

I think it would be good to explain why you ask to do that in the CONTRIBUTING.md, where it is asked.

Thanks!

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by itsmadhusudhan** [comment]
In my opinion it's right to host the images outside the git repository because 
1. Repository size will increase and people who pull  it to their local system to make changes end up downloading all images, which is not so good.
2. It's also easy to change the image if we want to by just changing the image url than putting the new image into the repo.
May be it can be explained there to give more clarity about this.

**Comment by thomaskuntzz** [comment]
Okay, cool, thanks, I'll add it to the CONTRIBUTING.md then

**Comment by thomaskuntzz** [comment]
Fixed by 8e81717

**Comment by systimotic** [comment]
@thomaskuntzz Can you please undo this commit and open a PR instead?

@Bouncey Do you have any input on why we're asking people to host images outside of this repo?

**Comment by thomaskuntzz** [comment]
Sure, I used the web editor to make this commit and I expected it to create a PR, but as I now have write access it committed directly...

I would have to make a new commit to revert the change and then open a PR, is that right?

**Comment by systimotic** [comment]
@thomaskuntzz Yep 😃 You can [use GitHub desktop to revert the commit](https://help.github.com/desktop/guides/contributing-to-projects/reverting-a-commit/), or [git revert](https://git-scm.com/docs/git-revert)

**Comment by thomaskuntzz** [comment]
Just figured that out, thanks! So I reverted my change: d503565

**Comment by thomaskuntzz** [comment]
I opened a PR for this: #8013
