### ISSUE TITLE
CSS is not loading

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guides#8071]
The CSS is not loading right now on https://guide.freecodecamp.org/
![20180214_21-08-26_firefox](https://user-images.githubusercontent.com/7262039/36225515-315625b4-11cb-11e8-90f8-4ee47ea2b529.png)

Reported by @erictleung on Gitter ([here](https://gitter.im/FreeCodeCamp/Contributors?at=5a84918593be87284db99a30)) and confirmed by @Asjas.

As far as I could find, the last working production version was [this one](https://5a834b55295b556a43cca18c--guide.netlify.com/) ([details](https://app.netlify.com/sites/guide/deploys/5a834b55295b556a43cca18c)). The first broken version is [this one](https://5a8394e7be40f160d1edd18b--guide.netlify.com/) ([details](https://app.netlify.com/sites/guide/deploys/5a8394e7be40f160d1edd18b)).

This is _not_ caused by the changes made in the commit made for that build (https://github.com/freeCodeCamp/guides/commit/4f087608616394f285db1592915ea5dc09e71803).

There _is_ a significant difference between the build logs of these versions. Notable is the Yarn update from 0.18.1 to 1.3.2, as well as some new messages at the end of the build:
```
3:03:22 AM: Started saving emacs cask dependencies
3:03:22 AM: Finished saving emacs cask dependencies
3:03:22 AM: Started saving maven dependencies
3:03:22 AM: Finished saving maven dependencies
3:03:22 AM: Started saving boot dependencies
3:03:22 AM: Finished saving boot dependencies
```

Some other messages have changed.

```diff
- 9:45:36 PM: Cached NPM modules
+ 3:03:16 AM: Started saving node modules
+ 3:03:16 AM: Finished saving node modules
- 9:45:37 PM: Saved Yarn cache
+ 3:03:16 AM: Started saving yarn cache
+ 3:03:22 AM: Finished saving yarn cache
- 9:45:37 PM: Saved Cache Directory
+ 3:03:22 AM: Started saving pip cache
+ 3:03:22 AM: Finished saving pip cache
```

```diff
- 9:45:37 PM: Build complete: exit code: 0
+ 3:03:22 AM: Build script success
```

My conclusion from this is that it looks like @netlify updated their build process. They now default to a newer version of Yarn.
I'm not sure if the newer Yarn version is causing this issue, but I'm fairly certain some change at Netlify is causing this issue.

I'll check if this can be fixed by updating the build config. Suggestions are welcome.

/cc @Bouncey @QuincyLarson

**Comment by systimotic** [comment]
It looks like @Bouncey just fixed it! 🎉
Can you confirm (and maybe elaborate a little bit on what the problem was and how you fixed it)?

**Comment by Bouncey** [comment]
Netlify bumped the yarn version from 0.18.1 to 1.3.2, whatever changes that brought in, our build cache was out of date and something broke.

I cleared the cache and rebuilt master, which worked. 

I then merged a PR to check the build cache was still valid, and that built successfully too.

I have locked us in to yarn@1.3.2 via build env variables

Auto publishing is back on and it seems that everything is working again

**Comment by systimotic** [comment]
Thanks for fixing this @Bouncey! 🎉 

I just checked and noticed that there is [something in the Netlify docs about the build cache](https://www.netlify.com/docs/build-gotchas/#build-cache) that I didn't see before.
Did you already get in touch with Netlify support? We might want to make them aware that this can happen when they update Yarn. They should probably clear build caches automatically on a Yarn update to prevent stuff like this.
