### ISSUE TITLE
Related to #5791 - search does not working

### ISSUE THREAD

**Issue by vidhya03** [freeCodeCamp/guides#8082]
This is similar to #5791. i couldn't reopen that issue hence submitting now

**Comment by johnkennedy9147** [comment]
@vidhya03 Search is working fine for me, could you provide any further information? 

For Example:
Confirm you are still experiencing the issue?
What OS and Browser (inc version) you are using?
Your location?
What you were doing on the site, eg navigated to main page directly and tried to search, or viewed an article then tried to search ...

thanks

**Comment by systimotic** [comment]
Thanks for reporting @vidhya03!

It works fine here as well 😕 It may have been a temporary outage on the search server. I pushed an update to the search page a couple of minutes ago, maybe that fixes your issue?
Can you confirm whether it's still broken? If it is, please share the information requested by @johnkennedy9147

**Comment by raisedadead** [comment]
Closing pending further updates from OP.
