### ISSUE TITLE
Would like to be assigned to writing Elixir guide

### ISSUE THREAD

**Issue by anandpotukchi** [freeCodeCamp/guides#8094]
I wish to edit the Elixir stubs.

**Comment by johnkennedy9147** [comment]
Hi @anandpotukchi No need to ask, just go ahead and edit any stubs or articles you wish. Then submit pull requests to submit. I recommend checking for pending PRs on any article you wish to edit, and reviewing CONTRIBUTING.md to ensure you conform to the necessary guidelines. There may be a significant delay before we get a chance to review your contribution(s) as we have a significant number of pending PRs. thanks
