### ISSUE TITLE
Why are there 2848 open pull requests?

### ISSUE THREAD

**Issue by sw-yx** [freeCodeCamp/guides#8096]
hi! i'm new here and im just wondering what the governance of this repo is. Are you actively accepting PRs or no? That matters to me as a potential contributor. thank you!

**Comment by Asjas** [comment]
Hi @sw-yx. Yes we do accept PRs. We have been actively merging PRs since Hacktoberfest when we had over 6000 PRs.

**Comment by raisedadead** [comment]
Hi @sw-yx please consider asking queries in 
[Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)
