### ISSUE TITLE
Update Yarn install instructions.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/guides#8097]
Yarn installation instructions in the contributing guide are not update to date with the latest recommended way.

https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#running-locally

These should be amended to use setup instructions from here instead:
https://yarnpkg.com/en/docs/install

A one liner pointing to this resource should be OK.

**Comment by cubiio** [comment]
Hi @raisedadead - I'd like to help out with this one.

**Comment by raisedadead** [comment]
Yes please @cubiio !

**Comment by kir486680** [comment]
I would like to help too!
