### ISSUE TITLE
Menu subfolders get resorted when they are expanded

### ISSUE THREAD

**Issue by joshalling** [freeCodeCamp/guides#8349]
There is some weird behavior with the guide menu where the subfolders are being moved around when they are expanded. 

Steps to reproduce
- go to https://guide.freecodecamp.org/
- click on Computer Science
- click on Data structures
- click on Quantum Computing
- click on Databases

I tested this in Chrome and Firefox

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
From my testing it seems to happen whenever any subfolder is opened.

I found a subfolder `Flink` in `Datascience Tools` that does the same. Marking this as `help wanted` if anyone wants to check why this happens and to open a PR to fix it.

**Comment by JimmayVV** [comment]
I believe I have this one figured out. Would love to submit a PR to solve it.

Seems the renderBody() function inside the NavPanel component was creating a discrete list of open menu items, and concatenating the filtered array of children (with the open menu items removed) underneath it.

It looks like the goal of this setup is to filter out the duplicate items that are in both the parent panel, and the sub panel, however I don't know if this is an ideal way to handle duplicates. In any event I'm exploring the contributions document and formatting a PR now :)
