### ISSUE TITLE
Need info on creating new folder in pages?

### ISSUE THREAD

**Issue by bharadwajpenydala** [freeCodeCamp/guides#849]
Hi, 

Tried to create a new folder(topic) under pages folder, cause of no write access, build failed. Is there a work around for this?

**Comment by dhcodes** [comment]
Did you add the folder locally? It should work if you:
a) make a new branch
b) make a new directory in `src/pages`
c) add an `index.md` file with a properly formatted title (like the others)

Then you can make a PR to against the master with the new directory.

**Comment by bharadwajpenydala** [comment]
No, I was looking to add directory over the remote. Thanks for the reply though, I'll do it locally.

**Comment by texas2010** [comment]
sorry about I closed PR. it is better to do that on the local. then send PR. thanks

**Comment by bharadwajpenydala** [comment]
It's okay @texas2010  :) I would have done the same if I were you :)

**Comment by jamesjpk123** [comment]
@texas2010 + @bharadwajpenydala is this issue resolved?

**Comment by texas2010** [comment]
it seems he didn't make PR but I close this issue because it is not guide repo issue. 

thanks
