### ISSUE TITLE
Incorrect top-level property in .eslintrc file

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/guides#87]
Should be `parserOptions` instead of `parserOption` in line number 2 in the .eslintrc file.
Node version: 8.2.1
npm version: 5.3.0
ESlint version:4.3.0
ESlint was giving the error as below.
![screenshot from 2017-07-23 22-51-13](https://user-images.githubusercontent.com/24691797/28502223-57160a74-700b-11e7-88ea-0917d103d24c.png)

**Comment by Bouncey** [comment]
I would welcome a PR to update `eslint` to v4 and adjust the `.eslintrc` accordingly

**Comment by invinciblycool** [comment]
Opened a PR with .eslintrc updated.

**Comment by Bouncey** [comment]
closed via #91
