### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by ChaituVR** [freeCodeCamp/guides#870]
Good for Beginners

- [ ] src/pages/agile/acceptance-criteria.md
 **Line 11:** The Acceptance Criteria will be the **beginnnings**

- [ ]  src/pages/algorithms/binary-search-trees/index.md
 **Line 19:** **### Relavant** videos on freeCodeCamp YouTube channel
  should be **Relevant**

- [ ]  src/pages/algorithms/binary-search-trees/index.md
 **Line 15:** For each node, its left **descendents** are less than the current node, which is less than the right **descendents**.
  can be **descendent nodes**

- [ ]  src/pages/algorithms/sorting-algorithms/merge-sort/index.md
 **Line 21:** **![Merge Sort algo]**
  should be **![Merge Sort Algorithm]**

- [ ]  src/pages/algorithms/sorting-algorithms/merge-sort/index.md
 **Line 29:** **### Relavant**
 should be **### Relevant**

- [ ]  src/pages/algorithms/sorting-algorithms/quick-sort/index.md
 **Line 6:** **Quick sort** is an **effiecient** divide and conquer sorting **alorithm**. It works by recursively partitioning the list **along** a pivot element.
  should be: **Quick Sort** is an **efficient** divide and conquer sorting algorithm. It works by recursively partitioning the list **along with** a pivot element.

- [ ] src/pages/algorithms/sorting-algorithms/quick-sort/index.md
 **Line 7:** Average case time **complecity** of Quick Sort is O(nlog(n)) with worst case time complexity being O(n^2). The choice of the pivot plays an important role in **determinng** the efficiency **fo** the sort algorithm.
  should be: Average case time **complexity** of Quick Sort is O(nlog(n)) with worst case time complexity being O(n^2). The choice of the pivot plays an important role in **determining** the efficiency **of** the sort algorithm.

- [ ]  src/pages/bootstrap/bootstrap-navigation-bar/index.md
 **Line 106:** #### **Collasping** the navbar
  should be:  #### **Collapsing** the navbar

- [ ]  src/pages/user-experience-design/content-audits/index.md
 **Line 12:** The content audit type will depend on the nature of the request, mostly for website **redesing** its required to do a full content inventory, **for project maintenance its a partial one!**
  should be:  The content audit type will depend on the nature of the request, mostly for website **redesign** its required to do a full content inventory, **for project maintenance, it's a partial one!**

**Comment by MattLawsonn** [comment]
I've just created a PR for all of these, should be good to go now
