### ISSUE TITLE
Git broken link

### ISSUE THREAD

**Issue by datruq** [freeCodeCamp/guides#874]
Hi there,

I was browsing the GIT guide, and I found a broken link 
![image](https://user-images.githubusercontent.com/17466312/31551289-b3e812e6-aff9-11e7-864e-15ab96a9ed37.png)

It's redirecting to https://guide.freecodecamp.org/git/git-merge/index.md
404 Page not found

Cheers!

**Comment by HKuz** [comment]
Hi @datruq - thanks for pointing this out! This (and a couple other broken links in the Git section) should be fixed in pending PR #633. I'll update that PR message to close this issue once it's merged. Thanks 🎉

**Comment by AugustasV** [comment]
I guess i fixed this page issue. Try to make PR.
